/*
 * pulp_nn_kernels.h
 * Nazareno Bruschi <nazareno.bruschi@unibo.it>
 *
 * Copyright (C) 2019-2020 University of Bologna
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef __PULPNN_KERNELS__
#define __PULPNN_KERNELS__

void pulp_nn_conv_u8_u8_i8(
	const uint8_t *pInBuffer,
	const uint16_t dim_in_x,
	const uint16_t dim_in_y,
	const uint16_t ch_in,
	const int8_t *pWeight,
	const uint16_t ch_out,
	const uint16_t dim_kernel_x,
	const uint16_t dim_kernel_y,
	const uint16_t padding_y_top,
	const uint16_t padding_y_bottom,
	const uint16_t padding_x_left,
	const uint16_t padding_x_right,
	const uint16_t stride_x,
	const uint16_t stride_y,
	const int8_t *bias,
	const uint16_t bias_shift,
	const int8_t out_shift,
	const uint16_t out_mult,
	uint8_t *pOutBuffer,
	const uint16_t dim_out_x,
	const uint16_t dim_out_y,
	int32_t *k,
	int32_t *lambda,
	uint8_t *pIm2ColBuffer,
	int flag_relu,
	int flag_batch_norm,
	unsigned int * memory_chan);

void pulp_nn_conv_u8_u8_i4(
	const uint8_t *pInBuffer,
	const uint16_t dim_in_x,
	const uint16_t dim_in_y,
	const uint16_t ch_in,
	const int8_t *pWeight,
	const uint16_t ch_out,
	const uint16_t dim_kernel_x,
	const uint16_t dim_kernel_y,
	const uint16_t padding_y_top,
	const uint16_t padding_y_bottom,
	const uint16_t padding_x_left,
	const uint16_t padding_x_right,
	const uint16_t stride_x,
	const uint16_t stride_y,
	const int8_t *bias,
	const uint16_t bias_shift,
	const int8_t out_shift,
	const uint16_t out_mult,
	uint8_t *pOutBuffer,
	const uint16_t dim_out_x,
	const uint16_t dim_out_y,
	int32_t *k,
	int32_t *lambda,
	uint8_t *pIm2ColBuffer,
	int flag_relu,
	int flag_batch_norm,
	unsigned int * memory_chan);

void pulp_nn_conv_u8_u8_i2(
	const uint8_t *pInBuffer,
	const uint16_t dim_in_x,
	const uint16_t dim_in_y,
	const uint16_t ch_in,
	const int8_t *pWeight,
	const uint16_t ch_out,
	const uint16_t dim_kernel_x,
	const uint16_t dim_kernel_y,
	const uint16_t padding_y_top,
	const uint16_t padding_y_bottom,
	const uint16_t padding_x_left,
	const uint16_t padding_x_right,
	const uint16_t stride_x,
	const uint16_t stride_y,
	const int8_t *bias,
	const uint16_t bias_shift,
	const int8_t out_shift,
	const uint16_t out_mult,
	uint8_t *pOutBuffer,
	const uint16_t dim_out_x,
	const uint16_t dim_out_y,
	int32_t *k,
	int32_t *lambda,
	uint8_t *pIm2ColBuffer,
	int flag_relu,
	int flag_batch_norm,
	unsigned int * memory_chan);

void pulp_nn_conv_u8_u4_i8(
	const uint8_t *pInBuffer,
	const uint16_t dim_in_x,
	const uint16_t dim_in_y,
	const uint16_t ch_in,
	const int8_t *pWeight,
	const uint16_t ch_out,
	const uint16_t dim_kernel_x,
	const uint16_t dim_kernel_y,
	const uint16_t padding_y_top,
	const uint16_t padding_y_bottom,
	const uint16_t padding_x_left,
	const uint16_t padding_x_right,
	const uint16_t stride_x,
	const uint16_t stride_y,
	const int8_t *bias,
	const uint16_t bias_shift,
	const int8_t out_shift,
	const uint16_t out_mult,
	uint8_t *pOutBuffer,
	const uint16_t dim_out_x,
	const uint16_t dim_out_y,
	int32_t *k,
	int32_t *lambda,
	uint8_t *pIm2ColBuffer,
	int flag_relu,
	int flag_batch_norm,
	unsigned int * memory_chan);

void pulp_nn_conv_u8_u4_i4(
	const uint8_t *pInBuffer,
	const uint16_t dim_in_x,
	const uint16_t dim_in_y,
	const uint16_t ch_in,
	const int8_t *pWeight,
	const uint16_t ch_out,
	const uint16_t dim_kernel_x,
	const uint16_t dim_kernel_y,
	const uint16_t padding_y_top,
	const uint16_t padding_y_bottom,
	const uint16_t padding_x_left,
	const uint16_t padding_x_right,
	const uint16_t stride_x,
	const uint16_t stride_y,
	const int8_t *bias,
	const uint16_t bias_shift,
	const int8_t out_shift,
	const uint16_t out_mult,
	uint8_t *pOutBuffer,
	const uint16_t dim_out_x,
	const uint16_t dim_out_y,
	int32_t *k,
	int32_t *lambda,
	uint8_t *pIm2ColBuffer,
	int flag_relu,
	int flag_batch_norm,
	unsigned int * memory_chan);

void pulp_nn_conv_u8_u4_i2(
	const uint8_t *pInBuffer,
	const uint16_t dim_in_x,
	const uint16_t dim_in_y,
	const uint16_t ch_in,
	const int8_t *pWeight,
	const uint16_t ch_out,
	const uint16_t dim_kernel_x,
	const uint16_t dim_kernel_y,
	const uint16_t padding_y_top,
	const uint16_t padding_y_bottom,
	const uint16_t padding_x_left,
	const uint16_t padding_x_right,
	const uint16_t stride_x,
	const uint16_t stride_y,
	const int8_t *bias,
	const uint16_t bias_shift,
	const int8_t out_shift,
	const uint16_t out_mult,
	uint8_t *pOutBuffer,
	const uint16_t dim_out_x,
	const uint16_t dim_out_y,
	int32_t *k,
	int32_t *lambda,
	uint8_t *pIm2ColBuffer,
	int flag_relu,
	int flag_batch_norm,
	unsigned int * memory_chan);

void pulp_nn_conv_u8_u2_i8(
	const uint8_t *pInBuffer,
	const uint16_t dim_in_x,
	const uint16_t dim_in_y,
	const uint16_t ch_in,
	const int8_t *pWeight,
	const uint16_t ch_out,
	const uint16_t dim_kernel_x,
	const uint16_t dim_kernel_y,
	const uint16_t padding_y_top,
	const uint16_t padding_y_bottom,
	const uint16_t padding_x_left,
	const uint16_t padding_x_right,
	const uint16_t stride_x,
	const uint16_t stride_y,
	const int8_t *bias,
	const uint16_t bias_shift,
	const int8_t out_shift,
	const uint16_t out_mult,
	uint8_t *pOutBuffer,
	const uint16_t dim_out_x,
	const uint16_t dim_out_y,
	int32_t *k,
	int32_t *lambda,
	uint8_t *pIm2ColBuffer,
	int flag_relu,
	int flag_batch_norm,
	unsigned int * memory_chan);

void pulp_nn_conv_u8_u2_i4(
	const uint8_t *pInBuffer,
	const uint16_t dim_in_x,
	const uint16_t dim_in_y,
	const uint16_t ch_in,
	const int8_t *pWeight,
	const uint16_t ch_out,
	const uint16_t dim_kernel_x,
	const uint16_t dim_kernel_y,
	const uint16_t padding_y_top,
	const uint16_t padding_y_bottom,
	const uint16_t padding_x_left,
	const uint16_t padding_x_right,
	const uint16_t stride_x,
	const uint16_t stride_y,
	const int8_t *bias,
	const uint16_t bias_shift,
	const int8_t out_shift,
	const uint16_t out_mult,
	uint8_t *pOutBuffer,
	const uint16_t dim_out_x,
	const uint16_t dim_out_y,
	int32_t *k,
	int32_t *lambda,
	uint8_t *pIm2ColBuffer,
	int flag_relu,
	int flag_batch_norm,
	unsigned int * memory_chan);

void pulp_nn_conv_u8_u2_i2(
	const uint8_t *pInBuffer,
	const uint16_t dim_in_x,
	const uint16_t dim_in_y,
	const uint16_t ch_in,
	const int8_t *pWeight,
	const uint16_t ch_out,
	const uint16_t dim_kernel_x,
	const uint16_t dim_kernel_y,
	const uint16_t padding_y_top,
	const uint16_t padding_y_bottom,
	const uint16_t padding_x_left,
	const uint16_t padding_x_right,
	const uint16_t stride_x,
	const uint16_t stride_y,
	const int8_t *bias,
	const uint16_t bias_shift,
	const int8_t out_shift,
	const uint16_t out_mult,
	uint8_t *pOutBuffer,
	const uint16_t dim_out_x,
	const uint16_t dim_out_y,
	int32_t *k,
	int32_t *lambda,
	uint8_t *pIm2ColBuffer,
	int flag_relu,
	int flag_batch_norm,
	unsigned int * memory_chan);

void pulp_nn_conv_u4_u8_i8(
	const uint8_t *pInBuffer,
	const uint16_t dim_in_x,
	const uint16_t dim_in_y,
	const uint16_t ch_in,
	const int8_t *pWeight,
	const uint16_t ch_out,
	const uint16_t dim_kernel_x,
	const uint16_t dim_kernel_y,
	const uint16_t padding_y_top,
	const uint16_t padding_y_bottom,
	const uint16_t padding_x_left,
	const uint16_t padding_x_right,
	const uint16_t stride_x,
	const uint16_t stride_y,
	const int8_t *bias,
	const uint16_t bias_shift,
	const int8_t out_shift,
	const uint16_t out_mult,
	uint8_t *pOutBuffer,
	const uint16_t dim_out_x,
	const uint16_t dim_out_y,
	int32_t *k,
	int32_t *lambda,
	uint8_t *pIm2ColBuffer,
	int flag_relu,
	int flag_batch_norm,
	unsigned int * memory_chan);

void pulp_nn_conv_u4_u8_i4(
	const uint8_t *pInBuffer,
	const uint16_t dim_in_x,
	const uint16_t dim_in_y,
	const uint16_t ch_in,
	const int8_t *pWeight,
	const uint16_t ch_out,
	const uint16_t dim_kernel_x,
	const uint16_t dim_kernel_y,
	const uint16_t padding_y_top,
	const uint16_t padding_y_bottom,
	const uint16_t padding_x_left,
	const uint16_t padding_x_right,
	const uint16_t stride_x,
	const uint16_t stride_y,
	const int8_t *bias,
	const uint16_t bias_shift,
	const int8_t out_shift,
	const uint16_t out_mult,
	uint8_t *pOutBuffer,
	const uint16_t dim_out_x,
	const uint16_t dim_out_y,
	int32_t *k,
	int32_t *lambda,
	uint8_t *pIm2ColBuffer,
	int flag_relu,
	int flag_batch_norm,
	unsigned int * memory_chan);

void pulp_nn_conv_u4_u8_i2(
	const uint8_t *pInBuffer,
	const uint16_t dim_in_x,
	const uint16_t dim_in_y,
	const uint16_t ch_in,
	const int8_t *pWeight,
	const uint16_t ch_out,
	const uint16_t dim_kernel_x,
	const uint16_t dim_kernel_y,
	const uint16_t padding_y_top,
	const uint16_t padding_y_bottom,
	const uint16_t padding_x_left,
	const uint16_t padding_x_right,
	const uint16_t stride_x,
	const uint16_t stride_y,
	const int8_t *bias,
	const uint16_t bias_shift,
	const int8_t out_shift,
	const uint16_t out_mult,
	uint8_t *pOutBuffer,
	const uint16_t dim_out_x,
	const uint16_t dim_out_y,
	int32_t *k,
	int32_t *lambda,
	uint8_t *pIm2ColBuffer,
	int flag_relu,
	int flag_batch_norm,
	unsigned int * memory_chan);

void pulp_nn_conv_u4_u4_i8(
	const uint8_t *pInBuffer,
	const uint16_t dim_in_x,
	const uint16_t dim_in_y,
	const uint16_t ch_in,
	const int8_t *pWeight,
	const uint16_t ch_out,
	const uint16_t dim_kernel_x,
	const uint16_t dim_kernel_y,
	const uint16_t padding_y_top,
	const uint16_t padding_y_bottom,
	const uint16_t padding_x_left,
	const uint16_t padding_x_right,
	const uint16_t stride_x,
	const uint16_t stride_y,
	const int8_t *bias,
	const uint16_t bias_shift,
	const int8_t out_shift,
	const uint16_t out_mult,
	uint8_t *pOutBuffer,
	const uint16_t dim_out_x,
	const uint16_t dim_out_y,
	int32_t *k,
	int32_t *lambda,
	uint8_t *pIm2ColBuffer,
	int flag_relu,
	int flag_batch_norm,
	unsigned int * memory_chan);

void pulp_nn_conv_u4_u4_i4(
	const uint8_t *pInBuffer,
	const uint16_t dim_in_x,
	const uint16_t dim_in_y,
	const uint16_t ch_in,
	const int8_t *pWeight,
	const uint16_t ch_out,
	const uint16_t dim_kernel_x,
	const uint16_t dim_kernel_y,
	const uint16_t padding_y_top,
	const uint16_t padding_y_bottom,
	const uint16_t padding_x_left,
	const uint16_t padding_x_right,
	const uint16_t stride_x,
	const uint16_t stride_y,
	const int8_t *bias,
	const uint16_t bias_shift,
	const int8_t out_shift,
	const uint16_t out_mult,
	uint8_t *pOutBuffer,
	const uint16_t dim_out_x,
	const uint16_t dim_out_y,
	int32_t *k,
	int32_t *lambda,
	uint8_t *pIm2ColBuffer,
	int flag_relu,
	int flag_batch_norm,
	unsigned int * memory_chan);

void pulp_nn_conv_u4_u4_i2(
	const uint8_t *pInBuffer,
	const uint16_t dim_in_x,
	const uint16_t dim_in_y,
	const uint16_t ch_in,
	const int8_t *pWeight,
	const uint16_t ch_out,
	const uint16_t dim_kernel_x,
	const uint16_t dim_kernel_y,
	const uint16_t padding_y_top,
	const uint16_t padding_y_bottom,
	const uint16_t padding_x_left,
	const uint16_t padding_x_right,
	const uint16_t stride_x,
	const uint16_t stride_y,
	const int8_t *bias,
	const uint16_t bias_shift,
	const int8_t out_shift,
	const uint16_t out_mult,
	uint8_t *pOutBuffer,
	const uint16_t dim_out_x,
	const uint16_t dim_out_y,
	int32_t *k,
	int32_t *lambda,
	uint8_t *pIm2ColBuffer,
	int flag_relu,
	int flag_batch_norm,
	unsigned int * memory_chan);

void pulp_nn_conv_u4_u2_i8(
	const uint8_t *pInBuffer,
	const uint16_t dim_in_x,
	const uint16_t dim_in_y,
	const uint16_t ch_in,
	const int8_t *pWeight,
	const uint16_t ch_out,
	const uint16_t dim_kernel_x,
	const uint16_t dim_kernel_y,
	const uint16_t padding_y_top,
	const uint16_t padding_y_bottom,
	const uint16_t padding_x_left,
	const uint16_t padding_x_right,
	const uint16_t stride_x,
	const uint16_t stride_y,
	const int8_t *bias,
	const uint16_t bias_shift,
	const int8_t out_shift,
	const uint16_t out_mult,
	uint8_t *pOutBuffer,
	const uint16_t dim_out_x,
	const uint16_t dim_out_y,
	int32_t *k,
	int32_t *lambda,
	uint8_t *pIm2ColBuffer,
	int flag_relu,
	int flag_batch_norm,
	unsigned int * memory_chan);

void pulp_nn_conv_u4_u2_i4(
	const uint8_t *pInBuffer,
	const uint16_t dim_in_x,
	const uint16_t dim_in_y,
	const uint16_t ch_in,
	const int8_t *pWeight,
	const uint16_t ch_out,
	const uint16_t dim_kernel_x,
	const uint16_t dim_kernel_y,
	const uint16_t padding_y_top,
	const uint16_t padding_y_bottom,
	const uint16_t padding_x_left,
	const uint16_t padding_x_right,
	const uint16_t stride_x,
	const uint16_t stride_y,
	const int8_t *bias,
	const uint16_t bias_shift,
	const int8_t out_shift,
	const uint16_t out_mult,
	uint8_t *pOutBuffer,
	const uint16_t dim_out_x,
	const uint16_t dim_out_y,
	int32_t *k,
	int32_t *lambda,
	uint8_t *pIm2ColBuffer,
	int flag_relu,
	int flag_batch_norm,
	unsigned int * memory_chan);

void pulp_nn_conv_u4_u2_i2(
	const uint8_t *pInBuffer,
	const uint16_t dim_in_x,
	const uint16_t dim_in_y,
	const uint16_t ch_in,
	const int8_t *pWeight,
	const uint16_t ch_out,
	const uint16_t dim_kernel_x,
	const uint16_t dim_kernel_y,
	const uint16_t padding_y_top,
	const uint16_t padding_y_bottom,
	const uint16_t padding_x_left,
	const uint16_t padding_x_right,
	const uint16_t stride_x,
	const uint16_t stride_y,
	const int8_t *bias,
	const uint16_t bias_shift,
	const int8_t out_shift,
	const uint16_t out_mult,
	uint8_t *pOutBuffer,
	const uint16_t dim_out_x,
	const uint16_t dim_out_y,
	int32_t *k,
	int32_t *lambda,
	uint8_t *pIm2ColBuffer,
	int flag_relu,
	int flag_batch_norm,
	unsigned int * memory_chan);

void pulp_nn_conv_u2_u8_i8(
	const uint8_t *pInBuffer,
	const uint16_t dim_in_x,
	const uint16_t dim_in_y,
	const uint16_t ch_in,
	const int8_t *pWeight,
	const uint16_t ch_out,
	const uint16_t dim_kernel_x,
	const uint16_t dim_kernel_y,
	const uint16_t padding_y_top,
	const uint16_t padding_y_bottom,
	const uint16_t padding_x_left,
	const uint16_t padding_x_right,
	const uint16_t stride_x,
	const uint16_t stride_y,
	const int8_t *bias,
	const uint16_t bias_shift,
	const int8_t out_shift,
	const uint16_t out_mult,
	uint8_t *pOutBuffer,
	const uint16_t dim_out_x,
	const uint16_t dim_out_y,
	int32_t *k,
	int32_t *lambda,
	uint8_t *pIm2ColBuffer,
	int flag_relu,
	int flag_batch_norm,
	unsigned int * memory_chan);

void pulp_nn_conv_u2_u8_i4(
	const uint8_t *pInBuffer,
	const uint16_t dim_in_x,
	const uint16_t dim_in_y,
	const uint16_t ch_in,
	const int8_t *pWeight,
	const uint16_t ch_out,
	const uint16_t dim_kernel_x,
	const uint16_t dim_kernel_y,
	const uint16_t padding_y_top,
	const uint16_t padding_y_bottom,
	const uint16_t padding_x_left,
	const uint16_t padding_x_right,
	const uint16_t stride_x,
	const uint16_t stride_y,
	const int8_t *bias,
	const uint16_t bias_shift,
	const int8_t out_shift,
	const uint16_t out_mult,
	uint8_t *pOutBuffer,
	const uint16_t dim_out_x,
	const uint16_t dim_out_y,
	int32_t *k,
	int32_t *lambda,
	uint8_t *pIm2ColBuffer,
	int flag_relu,
	int flag_batch_norm,
	unsigned int * memory_chan);

void pulp_nn_conv_u2_u8_i2(
	const uint8_t *pInBuffer,
	const uint16_t dim_in_x,
	const uint16_t dim_in_y,
	const uint16_t ch_in,
	const int8_t *pWeight,
	const uint16_t ch_out,
	const uint16_t dim_kernel_x,
	const uint16_t dim_kernel_y,
	const uint16_t padding_y_top,
	const uint16_t padding_y_bottom,
	const uint16_t padding_x_left,
	const uint16_t padding_x_right,
	const uint16_t stride_x,
	const uint16_t stride_y,
	const int8_t *bias,
	const uint16_t bias_shift,
	const int8_t out_shift,
	const uint16_t out_mult,
	uint8_t *pOutBuffer,
	const uint16_t dim_out_x,
	const uint16_t dim_out_y,
	int32_t *k,
	int32_t *lambda,
	uint8_t *pIm2ColBuffer,
	int flag_relu,
	int flag_batch_norm,
	unsigned int * memory_chan);

void pulp_nn_conv_u2_u4_i8(
	const uint8_t *pInBuffer,
	const uint16_t dim_in_x,
	const uint16_t dim_in_y,
	const uint16_t ch_in,
	const int8_t *pWeight,
	const uint16_t ch_out,
	const uint16_t dim_kernel_x,
	const uint16_t dim_kernel_y,
	const uint16_t padding_y_top,
	const uint16_t padding_y_bottom,
	const uint16_t padding_x_left,
	const uint16_t padding_x_right,
	const uint16_t stride_x,
	const uint16_t stride_y,
	const int8_t *bias,
	const uint16_t bias_shift,
	const int8_t out_shift,
	const uint16_t out_mult,
	uint8_t *pOutBuffer,
	const uint16_t dim_out_x,
	const uint16_t dim_out_y,
	int32_t *k,
	int32_t *lambda,
	uint8_t *pIm2ColBuffer,
	int flag_relu,
	int flag_batch_norm,
	unsigned int * memory_chan);

void pulp_nn_conv_u2_u4_i4(
	const uint8_t *pInBuffer,
	const uint16_t dim_in_x,
	const uint16_t dim_in_y,
	const uint16_t ch_in,
	const int8_t *pWeight,
	const uint16_t ch_out,
	const uint16_t dim_kernel_x,
	const uint16_t dim_kernel_y,
	const uint16_t padding_y_top,
	const uint16_t padding_y_bottom,
	const uint16_t padding_x_left,
	const uint16_t padding_x_right,
	const uint16_t stride_x,
	const uint16_t stride_y,
	const int8_t *bias,
	const uint16_t bias_shift,
	const int8_t out_shift,
	const uint16_t out_mult,
	uint8_t *pOutBuffer,
	const uint16_t dim_out_x,
	const uint16_t dim_out_y,
	int32_t *k,
	int32_t *lambda,
	uint8_t *pIm2ColBuffer,
	int flag_relu,
	int flag_batch_norm,
	unsigned int * memory_chan);

void pulp_nn_conv_u2_u4_i2(
	const uint8_t *pInBuffer,
	const uint16_t dim_in_x,
	const uint16_t dim_in_y,
	const uint16_t ch_in,
	const int8_t *pWeight,
	const uint16_t ch_out,
	const uint16_t dim_kernel_x,
	const uint16_t dim_kernel_y,
	const uint16_t padding_y_top,
	const uint16_t padding_y_bottom,
	const uint16_t padding_x_left,
	const uint16_t padding_x_right,
	const uint16_t stride_x,
	const uint16_t stride_y,
	const int8_t *bias,
	const uint16_t bias_shift,
	const int8_t out_shift,
	const uint16_t out_mult,
	uint8_t *pOutBuffer,
	const uint16_t dim_out_x,
	const uint16_t dim_out_y,
	int32_t *k,
	int32_t *lambda,
	uint8_t *pIm2ColBuffer,
	int flag_relu,
	int flag_batch_norm,
	unsigned int * memory_chan);

void pulp_nn_conv_u2_u2_i8(
	const uint8_t *pInBuffer,
	const uint16_t dim_in_x,
	const uint16_t dim_in_y,
	const uint16_t ch_in,
	const int8_t *pWeight,
	const uint16_t ch_out,
	const uint16_t dim_kernel_x,
	const uint16_t dim_kernel_y,
	const uint16_t padding_y_top,
	const uint16_t padding_y_bottom,
	const uint16_t padding_x_left,
	const uint16_t padding_x_right,
	const uint16_t stride_x,
	const uint16_t stride_y,
	const int8_t *bias,
	const uint16_t bias_shift,
	const int8_t out_shift,
	const uint16_t out_mult,
	uint8_t *pOutBuffer,
	const uint16_t dim_out_x,
	const uint16_t dim_out_y,
	int32_t *k,
	int32_t *lambda,
	uint8_t *pIm2ColBuffer,
	int flag_relu,
	int flag_batch_norm,
	unsigned int * memory_chan);

void pulp_nn_conv_u2_u2_i4(
	const uint8_t *pInBuffer,
	const uint16_t dim_in_x,
	const uint16_t dim_in_y,
	const uint16_t ch_in,
	const int8_t *pWeight,
	const uint16_t ch_out,
	const uint16_t dim_kernel_x,
	const uint16_t dim_kernel_y,
	const uint16_t padding_y_top,
	const uint16_t padding_y_bottom,
	const uint16_t padding_x_left,
	const uint16_t padding_x_right,
	const uint16_t stride_x,
	const uint16_t stride_y,
	const int8_t *bias,
	const uint16_t bias_shift,
	const int8_t out_shift,
	const uint16_t out_mult,
	uint8_t *pOutBuffer,
	const uint16_t dim_out_x,
	const uint16_t dim_out_y,
	int32_t *k,
	int32_t *lambda,
	uint8_t *pIm2ColBuffer,
	int flag_relu,
	int flag_batch_norm,
	unsigned int * memory_chan);

void pulp_nn_conv_u2_u2_i2(
	const uint8_t *pInBuffer,
	const uint16_t dim_in_x,
	const uint16_t dim_in_y,
	const uint16_t ch_in,
	const int8_t *pWeight,
	const uint16_t ch_out,
	const uint16_t dim_kernel_x,
	const uint16_t dim_kernel_y,
	const uint16_t padding_y_top,
	const uint16_t padding_y_bottom,
	const uint16_t padding_x_left,
	const uint16_t padding_x_right,
	const uint16_t stride_x,
	const uint16_t stride_y,
	const int8_t *bias,
	const uint16_t bias_shift,
	const int8_t out_shift,
	const uint16_t out_mult,
	uint8_t *pOutBuffer,
	const uint16_t dim_out_x,
	const uint16_t dim_out_y,
	int32_t *k,
	int32_t *lambda,
	uint8_t *pIm2ColBuffer,
	int flag_relu,
	int flag_batch_norm,
	unsigned int * memory_chan);

void pulp_nn_pointwise_u8_u8_i8(
	const uint8_t *pInBuffer,
	const uint16_t dim_in_x,
	const uint16_t dim_in_y,
	const uint16_t ch_in,
	const int8_t *pWeight,
	const uint16_t ch_out,
	const uint16_t dim_kernel_x,
	const uint16_t dim_kernel_y,
	const uint16_t padding_y_top,
	const uint16_t padding_y_bottom,
	const uint16_t padding_x_left,
	const uint16_t padding_x_right,
	const uint16_t stride_x,
	const uint16_t stride_y,
	const int8_t *bias,
	const uint16_t bias_shift,
	const int8_t out_shift,
	const uint16_t out_mult,
	uint8_t *pOutBuffer,
	const uint16_t dim_out_x,
	const uint16_t dim_out_y,
	int32_t *k,
	int32_t *lambda,
	uint8_t *pIm2ColBuffer,
	int flag_relu,
	int flag_batch_norm,
	unsigned int * memory_chan);

void pulp_nn_pointwise_u8_u8_i4(
	const uint8_t *pInBuffer,
	const uint16_t dim_in_x,
	const uint16_t dim_in_y,
	const uint16_t ch_in,
	const int8_t *pWeight,
	const uint16_t ch_out,
	const uint16_t dim_kernel_x,
	const uint16_t dim_kernel_y,
	const uint16_t padding_y_top,
	const uint16_t padding_y_bottom,
	const uint16_t padding_x_left,
	const uint16_t padding_x_right,
	const uint16_t stride_x,
	const uint16_t stride_y,
	const int8_t *bias,
	const uint16_t bias_shift,
	const int8_t out_shift,
	const uint16_t out_mult,
	uint8_t *pOutBuffer,
	const uint16_t dim_out_x,
	const uint16_t dim_out_y,
	int32_t *k,
	int32_t *lambda,
	uint8_t *pIm2ColBuffer,
	int flag_relu,
	int flag_batch_norm,
	unsigned int * memory_chan);

void pulp_nn_pointwise_u8_u8_i2(
	const uint8_t *pInBuffer,
	const uint16_t dim_in_x,
	const uint16_t dim_in_y,
	const uint16_t ch_in,
	const int8_t *pWeight,
	const uint16_t ch_out,
	const uint16_t dim_kernel_x,
	const uint16_t dim_kernel_y,
	const uint16_t padding_y_top,
	const uint16_t padding_y_bottom,
	const uint16_t padding_x_left,
	const uint16_t padding_x_right,
	const uint16_t stride_x,
	const uint16_t stride_y,
	const int8_t *bias,
	const uint16_t bias_shift,
	const int8_t out_shift,
	const uint16_t out_mult,
	uint8_t *pOutBuffer,
	const uint16_t dim_out_x,
	const uint16_t dim_out_y,
	int32_t *k,
	int32_t *lambda,
	uint8_t *pIm2ColBuffer,
	int flag_relu,
	int flag_batch_norm,
	unsigned int * memory_chan);

void pulp_nn_pointwise_u8_u4_i8(
	const uint8_t *pInBuffer,
	const uint16_t dim_in_x,
	const uint16_t dim_in_y,
	const uint16_t ch_in,
	const int8_t *pWeight,
	const uint16_t ch_out,
	const uint16_t dim_kernel_x,
	const uint16_t dim_kernel_y,
	const uint16_t padding_y_top,
	const uint16_t padding_y_bottom,
	const uint16_t padding_x_left,
	const uint16_t padding_x_right,
	const uint16_t stride_x,
	const uint16_t stride_y,
	const int8_t *bias,
	const uint16_t bias_shift,
	const int8_t out_shift,
	const uint16_t out_mult,
	uint8_t *pOutBuffer,
	const uint16_t dim_out_x,
	const uint16_t dim_out_y,
	int32_t *k,
	int32_t *lambda,
	uint8_t *pIm2ColBuffer,
	int flag_relu,
	int flag_batch_norm,
	unsigned int * memory_chan);

void pulp_nn_pointwise_u8_u4_i4(
	const uint8_t *pInBuffer,
	const uint16_t dim_in_x,
	const uint16_t dim_in_y,
	const uint16_t ch_in,
	const int8_t *pWeight,
	const uint16_t ch_out,
	const uint16_t dim_kernel_x,
	const uint16_t dim_kernel_y,
	const uint16_t padding_y_top,
	const uint16_t padding_y_bottom,
	const uint16_t padding_x_left,
	const uint16_t padding_x_right,
	const uint16_t stride_x,
	const uint16_t stride_y,
	const int8_t *bias,
	const uint16_t bias_shift,
	const int8_t out_shift,
	const uint16_t out_mult,
	uint8_t *pOutBuffer,
	const uint16_t dim_out_x,
	const uint16_t dim_out_y,
	int32_t *k,
	int32_t *lambda,
	uint8_t *pIm2ColBuffer,
	int flag_relu,
	int flag_batch_norm,
	unsigned int * memory_chan);

void pulp_nn_pointwise_u8_u4_i2(
	const uint8_t *pInBuffer,
	const uint16_t dim_in_x,
	const uint16_t dim_in_y,
	const uint16_t ch_in,
	const int8_t *pWeight,
	const uint16_t ch_out,
	const uint16_t dim_kernel_x,
	const uint16_t dim_kernel_y,
	const uint16_t padding_y_top,
	const uint16_t padding_y_bottom,
	const uint16_t padding_x_left,
	const uint16_t padding_x_right,
	const uint16_t stride_x,
	const uint16_t stride_y,
	const int8_t *bias,
	const uint16_t bias_shift,
	const int8_t out_shift,
	const uint16_t out_mult,
	uint8_t *pOutBuffer,
	const uint16_t dim_out_x,
	const uint16_t dim_out_y,
	int32_t *k,
	int32_t *lambda,
	uint8_t *pIm2ColBuffer,
	int flag_relu,
	int flag_batch_norm,
	unsigned int * memory_chan);

void pulp_nn_pointwise_u8_u2_i8(
	const uint8_t *pInBuffer,
	const uint16_t dim_in_x,
	const uint16_t dim_in_y,
	const uint16_t ch_in,
	const int8_t *pWeight,
	const uint16_t ch_out,
	const uint16_t dim_kernel_x,
	const uint16_t dim_kernel_y,
	const uint16_t padding_y_top,
	const uint16_t padding_y_bottom,
	const uint16_t padding_x_left,
	const uint16_t padding_x_right,
	const uint16_t stride_x,
	const uint16_t stride_y,
	const int8_t *bias,
	const uint16_t bias_shift,
	const int8_t out_shift,
	const uint16_t out_mult,
	uint8_t *pOutBuffer,
	const uint16_t dim_out_x,
	const uint16_t dim_out_y,
	int32_t *k,
	int32_t *lambda,
	uint8_t *pIm2ColBuffer,
	int flag_relu,
	int flag_batch_norm,
	unsigned int * memory_chan);

void pulp_nn_pointwise_u8_u2_i4(
	const uint8_t *pInBuffer,
	const uint16_t dim_in_x,
	const uint16_t dim_in_y,
	const uint16_t ch_in,
	const int8_t *pWeight,
	const uint16_t ch_out,
	const uint16_t dim_kernel_x,
	const uint16_t dim_kernel_y,
	const uint16_t padding_y_top,
	const uint16_t padding_y_bottom,
	const uint16_t padding_x_left,
	const uint16_t padding_x_right,
	const uint16_t stride_x,
	const uint16_t stride_y,
	const int8_t *bias,
	const uint16_t bias_shift,
	const int8_t out_shift,
	const uint16_t out_mult,
	uint8_t *pOutBuffer,
	const uint16_t dim_out_x,
	const uint16_t dim_out_y,
	int32_t *k,
	int32_t *lambda,
	uint8_t *pIm2ColBuffer,
	int flag_relu,
	int flag_batch_norm,
	unsigned int * memory_chan);

void pulp_nn_pointwise_u8_u2_i2(
	const uint8_t *pInBuffer,
	const uint16_t dim_in_x,
	const uint16_t dim_in_y,
	const uint16_t ch_in,
	const int8_t *pWeight,
	const uint16_t ch_out,
	const uint16_t dim_kernel_x,
	const uint16_t dim_kernel_y,
	const uint16_t padding_y_top,
	const uint16_t padding_y_bottom,
	const uint16_t padding_x_left,
	const uint16_t padding_x_right,
	const uint16_t stride_x,
	const uint16_t stride_y,
	const int8_t *bias,
	const uint16_t bias_shift,
	const int8_t out_shift,
	const uint16_t out_mult,
	uint8_t *pOutBuffer,
	const uint16_t dim_out_x,
	const uint16_t dim_out_y,
	int32_t *k,
	int32_t *lambda,
	uint8_t *pIm2ColBuffer,
	int flag_relu,
	int flag_batch_norm,
	unsigned int * memory_chan);

void pulp_nn_pointwise_u4_u8_i8(
	const uint8_t *pInBuffer,
	const uint16_t dim_in_x,
	const uint16_t dim_in_y,
	const uint16_t ch_in,
	const int8_t *pWeight,
	const uint16_t ch_out,
	const uint16_t dim_kernel_x,
	const uint16_t dim_kernel_y,
	const uint16_t padding_y_top,
	const uint16_t padding_y_bottom,
	const uint16_t padding_x_left,
	const uint16_t padding_x_right,
	const uint16_t stride_x,
	const uint16_t stride_y,
	const int8_t *bias,
	const uint16_t bias_shift,
	const int8_t out_shift,
	const uint16_t out_mult,
	uint8_t *pOutBuffer,
	const uint16_t dim_out_x,
	const uint16_t dim_out_y,
	int32_t *k,
	int32_t *lambda,
	uint8_t *pIm2ColBuffer,
	int flag_relu,
	int flag_batch_norm,
	unsigned int * memory_chan);

void pulp_nn_pointwise_u4_u8_i4(
	const uint8_t *pInBuffer,
	const uint16_t dim_in_x,
	const uint16_t dim_in_y,
	const uint16_t ch_in,
	const int8_t *pWeight,
	const uint16_t ch_out,
	const uint16_t dim_kernel_x,
	const uint16_t dim_kernel_y,
	const uint16_t padding_y_top,
	const uint16_t padding_y_bottom,
	const uint16_t padding_x_left,
	const uint16_t padding_x_right,
	const uint16_t stride_x,
	const uint16_t stride_y,
	const int8_t *bias,
	const uint16_t bias_shift,
	const int8_t out_shift,
	const uint16_t out_mult,
	uint8_t *pOutBuffer,
	const uint16_t dim_out_x,
	const uint16_t dim_out_y,
	int32_t *k,
	int32_t *lambda,
	uint8_t *pIm2ColBuffer,
	int flag_relu,
	int flag_batch_norm,
	unsigned int * memory_chan);

void pulp_nn_pointwise_u4_u8_i2(
	const uint8_t *pInBuffer,
	const uint16_t dim_in_x,
	const uint16_t dim_in_y,
	const uint16_t ch_in,
	const int8_t *pWeight,
	const uint16_t ch_out,
	const uint16_t dim_kernel_x,
	const uint16_t dim_kernel_y,
	const uint16_t padding_y_top,
	const uint16_t padding_y_bottom,
	const uint16_t padding_x_left,
	const uint16_t padding_x_right,
	const uint16_t stride_x,
	const uint16_t stride_y,
	const int8_t *bias,
	const uint16_t bias_shift,
	const int8_t out_shift,
	const uint16_t out_mult,
	uint8_t *pOutBuffer,
	const uint16_t dim_out_x,
	const uint16_t dim_out_y,
	int32_t *k,
	int32_t *lambda,
	uint8_t *pIm2ColBuffer,
	int flag_relu,
	int flag_batch_norm,
	unsigned int * memory_chan);

void pulp_nn_pointwise_u4_u4_i8(
	const uint8_t *pInBuffer,
	const uint16_t dim_in_x,
	const uint16_t dim_in_y,
	const uint16_t ch_in,
	const int8_t *pWeight,
	const uint16_t ch_out,
	const uint16_t dim_kernel_x,
	const uint16_t dim_kernel_y,
	const uint16_t padding_y_top,
	const uint16_t padding_y_bottom,
	const uint16_t padding_x_left,
	const uint16_t padding_x_right,
	const uint16_t stride_x,
	const uint16_t stride_y,
	const int8_t *bias,
	const uint16_t bias_shift,
	const int8_t out_shift,
	const uint16_t out_mult,
	uint8_t *pOutBuffer,
	const uint16_t dim_out_x,
	const uint16_t dim_out_y,
	int32_t *k,
	int32_t *lambda,
	uint8_t *pIm2ColBuffer,
	int flag_relu,
	int flag_batch_norm,
	unsigned int * memory_chan);

void pulp_nn_pointwise_u4_u4_i4(
	const uint8_t *pInBuffer,
	const uint16_t dim_in_x,
	const uint16_t dim_in_y,
	const uint16_t ch_in,
	const int8_t *pWeight,
	const uint16_t ch_out,
	const uint16_t dim_kernel_x,
	const uint16_t dim_kernel_y,
	const uint16_t padding_y_top,
	const uint16_t padding_y_bottom,
	const uint16_t padding_x_left,
	const uint16_t padding_x_right,
	const uint16_t stride_x,
	const uint16_t stride_y,
	const int8_t *bias,
	const uint16_t bias_shift,
	const int8_t out_shift,
	const uint16_t out_mult,
	uint8_t *pOutBuffer,
	const uint16_t dim_out_x,
	const uint16_t dim_out_y,
	int32_t *k,
	int32_t *lambda,
	uint8_t *pIm2ColBuffer,
	int flag_relu,
	int flag_batch_norm,
	unsigned int * memory_chan);

void pulp_nn_pointwise_u4_u4_i2(
	const uint8_t *pInBuffer,
	const uint16_t dim_in_x,
	const uint16_t dim_in_y,
	const uint16_t ch_in,
	const int8_t *pWeight,
	const uint16_t ch_out,
	const uint16_t dim_kernel_x,
	const uint16_t dim_kernel_y,
	const uint16_t padding_y_top,
	const uint16_t padding_y_bottom,
	const uint16_t padding_x_left,
	const uint16_t padding_x_right,
	const uint16_t stride_x,
	const uint16_t stride_y,
	const int8_t *bias,
	const uint16_t bias_shift,
	const int8_t out_shift,
	const uint16_t out_mult,
	uint8_t *pOutBuffer,
	const uint16_t dim_out_x,
	const uint16_t dim_out_y,
	int32_t *k,
	int32_t *lambda,
	uint8_t *pIm2ColBuffer,
	int flag_relu,
	int flag_batch_norm,
	unsigned int * memory_chan);

void pulp_nn_pointwise_u4_u2_i8(
	const uint8_t *pInBuffer,
	const uint16_t dim_in_x,
	const uint16_t dim_in_y,
	const uint16_t ch_in,
	const int8_t *pWeight,
	const uint16_t ch_out,
	const uint16_t dim_kernel_x,
	const uint16_t dim_kernel_y,
	const uint16_t padding_y_top,
	const uint16_t padding_y_bottom,
	const uint16_t padding_x_left,
	const uint16_t padding_x_right,
	const uint16_t stride_x,
	const uint16_t stride_y,
	const int8_t *bias,
	const uint16_t bias_shift,
	const int8_t out_shift,
	const uint16_t out_mult,
	uint8_t *pOutBuffer,
	const uint16_t dim_out_x,
	const uint16_t dim_out_y,
	int32_t *k,
	int32_t *lambda,
	uint8_t *pIm2ColBuffer,
	int flag_relu,
	int flag_batch_norm,
	unsigned int * memory_chan);

void pulp_nn_pointwise_u4_u2_i4(
	const uint8_t *pInBuffer,
	const uint16_t dim_in_x,
	const uint16_t dim_in_y,
	const uint16_t ch_in,
	const int8_t *pWeight,
	const uint16_t ch_out,
	const uint16_t dim_kernel_x,
	const uint16_t dim_kernel_y,
	const uint16_t padding_y_top,
	const uint16_t padding_y_bottom,
	const uint16_t padding_x_left,
	const uint16_t padding_x_right,
	const uint16_t stride_x,
	const uint16_t stride_y,
	const int8_t *bias,
	const uint16_t bias_shift,
	const int8_t out_shift,
	const uint16_t out_mult,
	uint8_t *pOutBuffer,
	const uint16_t dim_out_x,
	const uint16_t dim_out_y,
	int32_t *k,
	int32_t *lambda,
	uint8_t *pIm2ColBuffer,
	int flag_relu,
	int flag_batch_norm,
	unsigned int * memory_chan);

void pulp_nn_pointwise_u4_u2_i2(
	const uint8_t *pInBuffer,
	const uint16_t dim_in_x,
	const uint16_t dim_in_y,
	const uint16_t ch_in,
	const int8_t *pWeight,
	const uint16_t ch_out,
	const uint16_t dim_kernel_x,
	const uint16_t dim_kernel_y,
	const uint16_t padding_y_top,
	const uint16_t padding_y_bottom,
	const uint16_t padding_x_left,
	const uint16_t padding_x_right,
	const uint16_t stride_x,
	const uint16_t stride_y,
	const int8_t *bias,
	const uint16_t bias_shift,
	const int8_t out_shift,
	const uint16_t out_mult,
	uint8_t *pOutBuffer,
	const uint16_t dim_out_x,
	const uint16_t dim_out_y,
	int32_t *k,
	int32_t *lambda,
	uint8_t *pIm2ColBuffer,
	int flag_relu,
	int flag_batch_norm,
	unsigned int * memory_chan);

void pulp_nn_pointwise_u2_u8_i8(
	const uint8_t *pInBuffer,
	const uint16_t dim_in_x,
	const uint16_t dim_in_y,
	const uint16_t ch_in,
	const int8_t *pWeight,
	const uint16_t ch_out,
	const uint16_t dim_kernel_x,
	const uint16_t dim_kernel_y,
	const uint16_t padding_y_top,
	const uint16_t padding_y_bottom,
	const uint16_t padding_x_left,
	const uint16_t padding_x_right,
	const uint16_t stride_x,
	const uint16_t stride_y,
	const int8_t *bias,
	const uint16_t bias_shift,
	const int8_t out_shift,
	const uint16_t out_mult,
	uint8_t *pOutBuffer,
	const uint16_t dim_out_x,
	const uint16_t dim_out_y,
	int32_t *k,
	int32_t *lambda,
	uint8_t *pIm2ColBuffer,
	int flag_relu,
	int flag_batch_norm,
	unsigned int * memory_chan);

void pulp_nn_pointwise_u2_u8_i4(
	const uint8_t *pInBuffer,
	const uint16_t dim_in_x,
	const uint16_t dim_in_y,
	const uint16_t ch_in,
	const int8_t *pWeight,
	const uint16_t ch_out,
	const uint16_t dim_kernel_x,
	const uint16_t dim_kernel_y,
	const uint16_t padding_y_top,
	const uint16_t padding_y_bottom,
	const uint16_t padding_x_left,
	const uint16_t padding_x_right,
	const uint16_t stride_x,
	const uint16_t stride_y,
	const int8_t *bias,
	const uint16_t bias_shift,
	const int8_t out_shift,
	const uint16_t out_mult,
	uint8_t *pOutBuffer,
	const uint16_t dim_out_x,
	const uint16_t dim_out_y,
	int32_t *k,
	int32_t *lambda,
	uint8_t *pIm2ColBuffer,
	int flag_relu,
	int flag_batch_norm,
	unsigned int * memory_chan);

void pulp_nn_pointwise_u2_u8_i2(
	const uint8_t *pInBuffer,
	const uint16_t dim_in_x,
	const uint16_t dim_in_y,
	const uint16_t ch_in,
	const int8_t *pWeight,
	const uint16_t ch_out,
	const uint16_t dim_kernel_x,
	const uint16_t dim_kernel_y,
	const uint16_t padding_y_top,
	const uint16_t padding_y_bottom,
	const uint16_t padding_x_left,
	const uint16_t padding_x_right,
	const uint16_t stride_x,
	const uint16_t stride_y,
	const int8_t *bias,
	const uint16_t bias_shift,
	const int8_t out_shift,
	const uint16_t out_mult,
	uint8_t *pOutBuffer,
	const uint16_t dim_out_x,
	const uint16_t dim_out_y,
	int32_t *k,
	int32_t *lambda,
	uint8_t *pIm2ColBuffer,
	int flag_relu,
	int flag_batch_norm,
	unsigned int * memory_chan);

void pulp_nn_pointwise_u2_u4_i8(
	const uint8_t *pInBuffer,
	const uint16_t dim_in_x,
	const uint16_t dim_in_y,
	const uint16_t ch_in,
	const int8_t *pWeight,
	const uint16_t ch_out,
	const uint16_t dim_kernel_x,
	const uint16_t dim_kernel_y,
	const uint16_t padding_y_top,
	const uint16_t padding_y_bottom,
	const uint16_t padding_x_left,
	const uint16_t padding_x_right,
	const uint16_t stride_x,
	const uint16_t stride_y,
	const int8_t *bias,
	const uint16_t bias_shift,
	const int8_t out_shift,
	const uint16_t out_mult,
	uint8_t *pOutBuffer,
	const uint16_t dim_out_x,
	const uint16_t dim_out_y,
	int32_t *k,
	int32_t *lambda,
	uint8_t *pIm2ColBuffer,
	int flag_relu,
	int flag_batch_norm,
	unsigned int * memory_chan);

void pulp_nn_pointwise_u2_u4_i4(
	const uint8_t *pInBuffer,
	const uint16_t dim_in_x,
	const uint16_t dim_in_y,
	const uint16_t ch_in,
	const int8_t *pWeight,
	const uint16_t ch_out,
	const uint16_t dim_kernel_x,
	const uint16_t dim_kernel_y,
	const uint16_t padding_y_top,
	const uint16_t padding_y_bottom,
	const uint16_t padding_x_left,
	const uint16_t padding_x_right,
	const uint16_t stride_x,
	const uint16_t stride_y,
	const int8_t *bias,
	const uint16_t bias_shift,
	const int8_t out_shift,
	const uint16_t out_mult,
	uint8_t *pOutBuffer,
	const uint16_t dim_out_x,
	const uint16_t dim_out_y,
	int32_t *k,
	int32_t *lambda,
	uint8_t *pIm2ColBuffer,
	int flag_relu,
	int flag_batch_norm,
	unsigned int * memory_chan);

void pulp_nn_pointwise_u2_u4_i2(
	const uint8_t *pInBuffer,
	const uint16_t dim_in_x,
	const uint16_t dim_in_y,
	const uint16_t ch_in,
	const int8_t *pWeight,
	const uint16_t ch_out,
	const uint16_t dim_kernel_x,
	const uint16_t dim_kernel_y,
	const uint16_t padding_y_top,
	const uint16_t padding_y_bottom,
	const uint16_t padding_x_left,
	const uint16_t padding_x_right,
	const uint16_t stride_x,
	const uint16_t stride_y,
	const int8_t *bias,
	const uint16_t bias_shift,
	const int8_t out_shift,
	const uint16_t out_mult,
	uint8_t *pOutBuffer,
	const uint16_t dim_out_x,
	const uint16_t dim_out_y,
	int32_t *k,
	int32_t *lambda,
	uint8_t *pIm2ColBuffer,
	int flag_relu,
	int flag_batch_norm,
	unsigned int * memory_chan);

void pulp_nn_pointwise_u2_u2_i8(
	const uint8_t *pInBuffer,
	const uint16_t dim_in_x,
	const uint16_t dim_in_y,
	const uint16_t ch_in,
	const int8_t *pWeight,
	const uint16_t ch_out,
	const uint16_t dim_kernel_x,
	const uint16_t dim_kernel_y,
	const uint16_t padding_y_top,
	const uint16_t padding_y_bottom,
	const uint16_t padding_x_left,
	const uint16_t padding_x_right,
	const uint16_t stride_x,
	const uint16_t stride_y,
	const int8_t *bias,
	const uint16_t bias_shift,
	const int8_t out_shift,
	const uint16_t out_mult,
	uint8_t *pOutBuffer,
	const uint16_t dim_out_x,
	const uint16_t dim_out_y,
	int32_t *k,
	int32_t *lambda,
	uint8_t *pIm2ColBuffer,
	int flag_relu,
	int flag_batch_norm,
	unsigned int * memory_chan);

void pulp_nn_pointwise_u2_u2_i4(
	const uint8_t *pInBuffer,
	const uint16_t dim_in_x,
	const uint16_t dim_in_y,
	const uint16_t ch_in,
	const int8_t *pWeight,
	const uint16_t ch_out,
	const uint16_t dim_kernel_x,
	const uint16_t dim_kernel_y,
	const uint16_t padding_y_top,
	const uint16_t padding_y_bottom,
	const uint16_t padding_x_left,
	const uint16_t padding_x_right,
	const uint16_t stride_x,
	const uint16_t stride_y,
	const int8_t *bias,
	const uint16_t bias_shift,
	const int8_t out_shift,
	const uint16_t out_mult,
	uint8_t *pOutBuffer,
	const uint16_t dim_out_x,
	const uint16_t dim_out_y,
	int32_t *k,
	int32_t *lambda,
	uint8_t *pIm2ColBuffer,
	int flag_relu,
	int flag_batch_norm,
	unsigned int * memory_chan);

void pulp_nn_pointwise_u2_u2_i2(
	const uint8_t *pInBuffer,
	const uint16_t dim_in_x,
	const uint16_t dim_in_y,
	const uint16_t ch_in,
	const int8_t *pWeight,
	const uint16_t ch_out,
	const uint16_t dim_kernel_x,
	const uint16_t dim_kernel_y,
	const uint16_t padding_y_top,
	const uint16_t padding_y_bottom,
	const uint16_t padding_x_left,
	const uint16_t padding_x_right,
	const uint16_t stride_x,
	const uint16_t stride_y,
	const int8_t *bias,
	const uint16_t bias_shift,
	const int8_t out_shift,
	const uint16_t out_mult,
	uint8_t *pOutBuffer,
	const uint16_t dim_out_x,
	const uint16_t dim_out_y,
	int32_t *k,
	int32_t *lambda,
	uint8_t *pIm2ColBuffer,
	int flag_relu,
	int flag_batch_norm,
	unsigned int * memory_chan);

uint8_t *pulp_nn_matmul_u8_i8(
	const int8_t * pWeight,
	uint8_t * pInBuffer,
	uint16_t ch_out,
	uint16_t num_col_im2col,
	uint16_t bias_shift,
	int8_t out_shift,
	uint16_t out_mult,
	int32_t *k,
	int32_t *lambda,
	const int8_t * bias,
	uint8_t * pOut,
	int flag_relu,
	int flag_batch_norm);

uint8_t *pulp_nn_matmul_u8_i4(
	const int8_t * pWeight,
	uint8_t * pInBuffer,
	uint16_t ch_out,
	uint16_t num_col_im2col,
	uint16_t bias_shift,
	int8_t out_shift,
	uint16_t out_mult,
	int32_t *k,
	int32_t *lambda,
	const int8_t * bias,
	uint8_t * pOut,
	int flag_relu,
	int flag_batch_norm);

uint8_t *pulp_nn_matmul_u8_i2(
	const int8_t * pWeight,
	uint8_t * pInBuffer,
	uint16_t ch_out,
	uint16_t num_col_im2col,
	uint16_t bias_shift,
	int8_t out_shift,
	uint16_t out_mult,
	int32_t *k,
	int32_t *lambda,
	const int8_t * bias,
	uint8_t * pOut,
	int flag_relu,
	int flag_batch_norm);

uint8_t *pulp_nn_matmul_u4_i8(
	const int8_t * pWeight,
	uint8_t * pInBuffer,
	uint16_t ch_out,
	uint16_t num_col_im2col,
	uint16_t bias_shift,
	int8_t out_shift,
	uint16_t out_mult,
	int32_t *k,
	int32_t *lambda,
	const int8_t * bias,
	uint8_t * pOut,
	int flag_relu,
	int flag_batch_norm);

uint8_t *pulp_nn_matmul_u4_i4(
	const int8_t * pWeight,
	uint8_t * pInBuffer,
	uint16_t ch_out,
	uint16_t num_col_im2col,
	uint16_t bias_shift,
	int8_t out_shift,
	uint16_t out_mult,
	int32_t *k,
	int32_t *lambda,
	const int8_t * bias,
	uint8_t * pOut,
	int flag_relu,
	int flag_batch_norm);

uint8_t *pulp_nn_matmul_u4_i2(
	const int8_t * pWeight,
	uint8_t * pInBuffer,
	uint16_t ch_out,
	uint16_t num_col_im2col,
	uint16_t bias_shift,
	int8_t out_shift,
	uint16_t out_mult,
	int32_t *k,
	int32_t *lambda,
	const int8_t * bias,
	uint8_t * pOut,
	int flag_relu,
	int flag_batch_norm);

uint8_t *pulp_nn_matmul_u2_i8(
	const int8_t * pWeight,
	uint8_t * pInBuffer,
	uint16_t ch_out,
	uint16_t num_col_im2col,
	uint16_t bias_shift,
	int8_t out_shift,
	uint16_t out_mult,
	int32_t *k,
	int32_t *lambda,
	const int8_t * bias,
	uint8_t * pOut,
	int flag_relu,
	int flag_batch_norm);

uint8_t *pulp_nn_matmul_u2_i4(
	const int8_t * pWeight,
	uint8_t * pInBuffer,
	uint16_t ch_out,
	uint16_t num_col_im2col,
	uint16_t bias_shift,
	int8_t out_shift,
	uint16_t out_mult,
	int32_t *k,
	int32_t *lambda,
	const int8_t * bias,
	uint8_t * pOut,
	int flag_relu,
	int flag_batch_norm);

uint8_t *pulp_nn_matmul_u2_i2(
	const int8_t * pWeight,
	uint8_t * pInBuffer,
	uint16_t ch_out,
	uint16_t num_col_im2col,
	uint16_t bias_shift,
	int8_t out_shift,
	uint16_t out_mult,
	int32_t *k,
	int32_t *lambda,
	const int8_t * bias,
	uint8_t * pOut,
	int flag_relu,
	int flag_batch_norm);

void pulp_nn_depthwise_u8_u8_i8(
	const uint8_t * pInBuffer,
	const uint16_t dim_in_x,
	const uint16_t dim_in_y,
	const uint16_t ch_in,
	const int8_t * pWeightBuffer,
	const uint16_t ch_out,
	const uint16_t dim_kernel_x,
	const uint16_t dim_kernel_y,
	const uint16_t padding_y_top,
	const uint16_t padding_y_bottom,
	const uint16_t padding_x_left,
	const uint16_t padding_x_right,
	const uint16_t stride_x,
	const uint16_t stride_y,
	const int8_t * bias,
	const uint16_t bias_shift,
	const int8_t out_shift,
	const uint16_t out_mult,
	uint8_t * pOutBuffer,
	const uint16_t dim_out_x,
	const uint16_t dim_out_y,
	int32_t *k,
	int32_t *lambda,
	uint8_t * pIm2ColBuffer,
	int8_t * pWtBuffer,
	int flag_relu,
	int flag_batch_norm,
	unsigned int * memory_chan);

void pulp_nn_depthwise_u8_u8_i4(
	const uint8_t * pInBuffer,
	const uint16_t dim_in_x,
	const uint16_t dim_in_y,
	const uint16_t ch_in,
	const int8_t * pWeightBuffer,
	const uint16_t ch_out,
	const uint16_t dim_kernel_x,
	const uint16_t dim_kernel_y,
	const uint16_t padding_y_top,
	const uint16_t padding_y_bottom,
	const uint16_t padding_x_left,
	const uint16_t padding_x_right,
	const uint16_t stride_x,
	const uint16_t stride_y,
	const int8_t * bias,
	const uint16_t bias_shift,
	const int8_t out_shift,
	const uint16_t out_mult,
	uint8_t * pOutBuffer,
	const uint16_t dim_out_x,
	const uint16_t dim_out_y,
	int32_t *k,
	int32_t *lambda,
	uint8_t * pIm2ColBuffer,
	int8_t * pWtBuffer,
	int flag_relu,
	int flag_batch_norm,
	unsigned int * memory_chan);

void pulp_nn_depthwise_u8_u8_i2(
	const uint8_t * pInBuffer,
	const uint16_t dim_in_x,
	const uint16_t dim_in_y,
	const uint16_t ch_in,
	const int8_t * pWeightBuffer,
	const uint16_t ch_out,
	const uint16_t dim_kernel_x,
	const uint16_t dim_kernel_y,
	const uint16_t padding_y_top,
	const uint16_t padding_y_bottom,
	const uint16_t padding_x_left,
	const uint16_t padding_x_right,
	const uint16_t stride_x,
	const uint16_t stride_y,
	const int8_t * bias,
	const uint16_t bias_shift,
	const int8_t out_shift,
	const uint16_t out_mult,
	uint8_t * pOutBuffer,
	const uint16_t dim_out_x,
	const uint16_t dim_out_y,
	int32_t *k,
	int32_t *lambda,
	uint8_t * pIm2ColBuffer,
	int8_t * pWtBuffer,
	int flag_relu,
	int flag_batch_norm,
	unsigned int * memory_chan);

void pulp_nn_depthwise_u8_u4_i8(
	const uint8_t * pInBuffer,
	const uint16_t dim_in_x,
	const uint16_t dim_in_y,
	const uint16_t ch_in,
	const int8_t * pWeightBuffer,
	const uint16_t ch_out,
	const uint16_t dim_kernel_x,
	const uint16_t dim_kernel_y,
	const uint16_t padding_y_top,
	const uint16_t padding_y_bottom,
	const uint16_t padding_x_left,
	const uint16_t padding_x_right,
	const uint16_t stride_x,
	const uint16_t stride_y,
	const int8_t * bias,
	const uint16_t bias_shift,
	const int8_t out_shift,
	const uint16_t out_mult,
	uint8_t * pOutBuffer,
	const uint16_t dim_out_x,
	const uint16_t dim_out_y,
	int32_t *k,
	int32_t *lambda,
	uint8_t * pIm2ColBuffer,
	int8_t * pWtBuffer,
	int flag_relu,
	int flag_batch_norm,
	unsigned int * memory_chan);

void pulp_nn_depthwise_u8_u4_i4(
	const uint8_t * pInBuffer,
	const uint16_t dim_in_x,
	const uint16_t dim_in_y,
	const uint16_t ch_in,
	const int8_t * pWeightBuffer,
	const uint16_t ch_out,
	const uint16_t dim_kernel_x,
	const uint16_t dim_kernel_y,
	const uint16_t padding_y_top,
	const uint16_t padding_y_bottom,
	const uint16_t padding_x_left,
	const uint16_t padding_x_right,
	const uint16_t stride_x,
	const uint16_t stride_y,
	const int8_t * bias,
	const uint16_t bias_shift,
	const int8_t out_shift,
	const uint16_t out_mult,
	uint8_t * pOutBuffer,
	const uint16_t dim_out_x,
	const uint16_t dim_out_y,
	int32_t *k,
	int32_t *lambda,
	uint8_t * pIm2ColBuffer,
	int8_t * pWtBuffer,
	int flag_relu,
	int flag_batch_norm,
	unsigned int * memory_chan);

void pulp_nn_depthwise_u8_u4_i2(
	const uint8_t * pInBuffer,
	const uint16_t dim_in_x,
	const uint16_t dim_in_y,
	const uint16_t ch_in,
	const int8_t * pWeightBuffer,
	const uint16_t ch_out,
	const uint16_t dim_kernel_x,
	const uint16_t dim_kernel_y,
	const uint16_t padding_y_top,
	const uint16_t padding_y_bottom,
	const uint16_t padding_x_left,
	const uint16_t padding_x_right,
	const uint16_t stride_x,
	const uint16_t stride_y,
	const int8_t * bias,
	const uint16_t bias_shift,
	const int8_t out_shift,
	const uint16_t out_mult,
	uint8_t * pOutBuffer,
	const uint16_t dim_out_x,
	const uint16_t dim_out_y,
	int32_t *k,
	int32_t *lambda,
	uint8_t * pIm2ColBuffer,
	int8_t * pWtBuffer,
	int flag_relu,
	int flag_batch_norm,
	unsigned int * memory_chan);

void pulp_nn_depthwise_u8_u2_i8(
	const uint8_t * pInBuffer,
	const uint16_t dim_in_x,
	const uint16_t dim_in_y,
	const uint16_t ch_in,
	const int8_t * pWeightBuffer,
	const uint16_t ch_out,
	const uint16_t dim_kernel_x,
	const uint16_t dim_kernel_y,
	const uint16_t padding_y_top,
	const uint16_t padding_y_bottom,
	const uint16_t padding_x_left,
	const uint16_t padding_x_right,
	const uint16_t stride_x,
	const uint16_t stride_y,
	const int8_t * bias,
	const uint16_t bias_shift,
	const int8_t out_shift,
	const uint16_t out_mult,
	uint8_t * pOutBuffer,
	const uint16_t dim_out_x,
	const uint16_t dim_out_y,
	int32_t *k,
	int32_t *lambda,
	uint8_t * pIm2ColBuffer,
	int8_t * pWtBuffer,
	int flag_relu,
	int flag_batch_norm,
	unsigned int * memory_chan);

void pulp_nn_depthwise_u8_u2_i4(
	const uint8_t * pInBuffer,
	const uint16_t dim_in_x,
	const uint16_t dim_in_y,
	const uint16_t ch_in,
	const int8_t * pWeightBuffer,
	const uint16_t ch_out,
	const uint16_t dim_kernel_x,
	const uint16_t dim_kernel_y,
	const uint16_t padding_y_top,
	const uint16_t padding_y_bottom,
	const uint16_t padding_x_left,
	const uint16_t padding_x_right,
	const uint16_t stride_x,
	const uint16_t stride_y,
	const int8_t * bias,
	const uint16_t bias_shift,
	const int8_t out_shift,
	const uint16_t out_mult,
	uint8_t * pOutBuffer,
	const uint16_t dim_out_x,
	const uint16_t dim_out_y,
	int32_t *k,
	int32_t *lambda,
	uint8_t * pIm2ColBuffer,
	int8_t * pWtBuffer,
	int flag_relu,
	int flag_batch_norm,
	unsigned int * memory_chan);

void pulp_nn_depthwise_u8_u2_i2(
	const uint8_t * pInBuffer,
	const uint16_t dim_in_x,
	const uint16_t dim_in_y,
	const uint16_t ch_in,
	const int8_t * pWeightBuffer,
	const uint16_t ch_out,
	const uint16_t dim_kernel_x,
	const uint16_t dim_kernel_y,
	const uint16_t padding_y_top,
	const uint16_t padding_y_bottom,
	const uint16_t padding_x_left,
	const uint16_t padding_x_right,
	const uint16_t stride_x,
	const uint16_t stride_y,
	const int8_t * bias,
	const uint16_t bias_shift,
	const int8_t out_shift,
	const uint16_t out_mult,
	uint8_t * pOutBuffer,
	const uint16_t dim_out_x,
	const uint16_t dim_out_y,
	int32_t *k,
	int32_t *lambda,
	uint8_t * pIm2ColBuffer,
	int8_t * pWtBuffer,
	int flag_relu,
	int flag_batch_norm,
	unsigned int * memory_chan);

void pulp_nn_depthwise_u4_u8_i8(
	const uint8_t * pInBuffer,
	const uint16_t dim_in_x,
	const uint16_t dim_in_y,
	const uint16_t ch_in,
	const int8_t * pWeightBuffer,
	const uint16_t ch_out,
	const uint16_t dim_kernel_x,
	const uint16_t dim_kernel_y,
	const uint16_t padding_y_top,
	const uint16_t padding_y_bottom,
	const uint16_t padding_x_left,
	const uint16_t padding_x_right,
	const uint16_t stride_x,
	const uint16_t stride_y,
	const int8_t * bias,
	const uint16_t bias_shift,
	const int8_t out_shift,
	const uint16_t out_mult,
	uint8_t * pOutBuffer,
	const uint16_t dim_out_x,
	const uint16_t dim_out_y,
	int32_t *k,
	int32_t *lambda,
	uint8_t * pIm2ColBuffer,
	int8_t * pWtBuffer,
	int flag_relu,
	int flag_batch_norm,
	unsigned int * memory_chan);

void pulp_nn_depthwise_u4_u8_i4(
	const uint8_t * pInBuffer,
	const uint16_t dim_in_x,
	const uint16_t dim_in_y,
	const uint16_t ch_in,
	const int8_t * pWeightBuffer,
	const uint16_t ch_out,
	const uint16_t dim_kernel_x,
	const uint16_t dim_kernel_y,
	const uint16_t padding_y_top,
	const uint16_t padding_y_bottom,
	const uint16_t padding_x_left,
	const uint16_t padding_x_right,
	const uint16_t stride_x,
	const uint16_t stride_y,
	const int8_t * bias,
	const uint16_t bias_shift,
	const int8_t out_shift,
	const uint16_t out_mult,
	uint8_t * pOutBuffer,
	const uint16_t dim_out_x,
	const uint16_t dim_out_y,
	int32_t *k,
	int32_t *lambda,
	uint8_t * pIm2ColBuffer,
	int8_t * pWtBuffer,
	int flag_relu,
	int flag_batch_norm,
	unsigned int * memory_chan);

void pulp_nn_depthwise_u4_u8_i2(
	const uint8_t * pInBuffer,
	const uint16_t dim_in_x,
	const uint16_t dim_in_y,
	const uint16_t ch_in,
	const int8_t * pWeightBuffer,
	const uint16_t ch_out,
	const uint16_t dim_kernel_x,
	const uint16_t dim_kernel_y,
	const uint16_t padding_y_top,
	const uint16_t padding_y_bottom,
	const uint16_t padding_x_left,
	const uint16_t padding_x_right,
	const uint16_t stride_x,
	const uint16_t stride_y,
	const int8_t * bias,
	const uint16_t bias_shift,
	const int8_t out_shift,
	const uint16_t out_mult,
	uint8_t * pOutBuffer,
	const uint16_t dim_out_x,
	const uint16_t dim_out_y,
	int32_t *k,
	int32_t *lambda,
	uint8_t * pIm2ColBuffer,
	int8_t * pWtBuffer,
	int flag_relu,
	int flag_batch_norm,
	unsigned int * memory_chan);

void pulp_nn_depthwise_u4_u4_i8(
	const uint8_t * pInBuffer,
	const uint16_t dim_in_x,
	const uint16_t dim_in_y,
	const uint16_t ch_in,
	const int8_t * pWeightBuffer,
	const uint16_t ch_out,
	const uint16_t dim_kernel_x,
	const uint16_t dim_kernel_y,
	const uint16_t padding_y_top,
	const uint16_t padding_y_bottom,
	const uint16_t padding_x_left,
	const uint16_t padding_x_right,
	const uint16_t stride_x,
	const uint16_t stride_y,
	const int8_t * bias,
	const uint16_t bias_shift,
	const int8_t out_shift,
	const uint16_t out_mult,
	uint8_t * pOutBuffer,
	const uint16_t dim_out_x,
	const uint16_t dim_out_y,
	int32_t *k,
	int32_t *lambda,
	uint8_t * pIm2ColBuffer,
	int8_t * pWtBuffer,
	int flag_relu,
	int flag_batch_norm,
	unsigned int * memory_chan);

void pulp_nn_depthwise_u4_u4_i4(
	const uint8_t * pInBuffer,
	const uint16_t dim_in_x,
	const uint16_t dim_in_y,
	const uint16_t ch_in,
	const int8_t * pWeightBuffer,
	const uint16_t ch_out,
	const uint16_t dim_kernel_x,
	const uint16_t dim_kernel_y,
	const uint16_t padding_y_top,
	const uint16_t padding_y_bottom,
	const uint16_t padding_x_left,
	const uint16_t padding_x_right,
	const uint16_t stride_x,
	const uint16_t stride_y,
	const int8_t * bias,
	const uint16_t bias_shift,
	const int8_t out_shift,
	const uint16_t out_mult,
	uint8_t * pOutBuffer,
	const uint16_t dim_out_x,
	const uint16_t dim_out_y,
	int32_t *k,
	int32_t *lambda,
	uint8_t * pIm2ColBuffer,
	int8_t * pWtBuffer,
	int flag_relu,
	int flag_batch_norm,
	unsigned int * memory_chan);

void pulp_nn_depthwise_u4_u4_i2(
	const uint8_t * pInBuffer,
	const uint16_t dim_in_x,
	const uint16_t dim_in_y,
	const uint16_t ch_in,
	const int8_t * pWeightBuffer,
	const uint16_t ch_out,
	const uint16_t dim_kernel_x,
	const uint16_t dim_kernel_y,
	const uint16_t padding_y_top,
	const uint16_t padding_y_bottom,
	const uint16_t padding_x_left,
	const uint16_t padding_x_right,
	const uint16_t stride_x,
	const uint16_t stride_y,
	const int8_t * bias,
	const uint16_t bias_shift,
	const int8_t out_shift,
	const uint16_t out_mult,
	uint8_t * pOutBuffer,
	const uint16_t dim_out_x,
	const uint16_t dim_out_y,
	int32_t *k,
	int32_t *lambda,
	uint8_t * pIm2ColBuffer,
	int8_t * pWtBuffer,
	int flag_relu,
	int flag_batch_norm,
	unsigned int * memory_chan);

void pulp_nn_depthwise_u4_u2_i8(
	const uint8_t * pInBuffer,
	const uint16_t dim_in_x,
	const uint16_t dim_in_y,
	const uint16_t ch_in,
	const int8_t * pWeightBuffer,
	const uint16_t ch_out,
	const uint16_t dim_kernel_x,
	const uint16_t dim_kernel_y,
	const uint16_t padding_y_top,
	const uint16_t padding_y_bottom,
	const uint16_t padding_x_left,
	const uint16_t padding_x_right,
	const uint16_t stride_x,
	const uint16_t stride_y,
	const int8_t * bias,
	const uint16_t bias_shift,
	const int8_t out_shift,
	const uint16_t out_mult,
	uint8_t * pOutBuffer,
	const uint16_t dim_out_x,
	const uint16_t dim_out_y,
	int32_t *k,
	int32_t *lambda,
	uint8_t * pIm2ColBuffer,
	int8_t * pWtBuffer,
	int flag_relu,
	int flag_batch_norm,
	unsigned int * memory_chan);

void pulp_nn_depthwise_u4_u2_i4(
	const uint8_t * pInBuffer,
	const uint16_t dim_in_x,
	const uint16_t dim_in_y,
	const uint16_t ch_in,
	const int8_t * pWeightBuffer,
	const uint16_t ch_out,
	const uint16_t dim_kernel_x,
	const uint16_t dim_kernel_y,
	const uint16_t padding_y_top,
	const uint16_t padding_y_bottom,
	const uint16_t padding_x_left,
	const uint16_t padding_x_right,
	const uint16_t stride_x,
	const uint16_t stride_y,
	const int8_t * bias,
	const uint16_t bias_shift,
	const int8_t out_shift,
	const uint16_t out_mult,
	uint8_t * pOutBuffer,
	const uint16_t dim_out_x,
	const uint16_t dim_out_y,
	int32_t *k,
	int32_t *lambda,
	uint8_t * pIm2ColBuffer,
	int8_t * pWtBuffer,
	int flag_relu,
	int flag_batch_norm,
	unsigned int * memory_chan);

void pulp_nn_depthwise_u4_u2_i2(
	const uint8_t * pInBuffer,
	const uint16_t dim_in_x,
	const uint16_t dim_in_y,
	const uint16_t ch_in,
	const int8_t * pWeightBuffer,
	const uint16_t ch_out,
	const uint16_t dim_kernel_x,
	const uint16_t dim_kernel_y,
	const uint16_t padding_y_top,
	const uint16_t padding_y_bottom,
	const uint16_t padding_x_left,
	const uint16_t padding_x_right,
	const uint16_t stride_x,
	const uint16_t stride_y,
	const int8_t * bias,
	const uint16_t bias_shift,
	const int8_t out_shift,
	const uint16_t out_mult,
	uint8_t * pOutBuffer,
	const uint16_t dim_out_x,
	const uint16_t dim_out_y,
	int32_t *k,
	int32_t *lambda,
	uint8_t * pIm2ColBuffer,
	int8_t * pWtBuffer,
	int flag_relu,
	int flag_batch_norm,
	unsigned int * memory_chan);

void pulp_nn_depthwise_u2_u8_i8(
	const uint8_t * pInBuffer,
	const uint16_t dim_in_x,
	const uint16_t dim_in_y,
	const uint16_t ch_in,
	const int8_t * pWeightBuffer,
	const uint16_t ch_out,
	const uint16_t dim_kernel_x,
	const uint16_t dim_kernel_y,
	const uint16_t padding_y_top,
	const uint16_t padding_y_bottom,
	const uint16_t padding_x_left,
	const uint16_t padding_x_right,
	const uint16_t stride_x,
	const uint16_t stride_y,
	const int8_t * bias,
	const uint16_t bias_shift,
	const int8_t out_shift,
	const uint16_t out_mult,
	uint8_t * pOutBuffer,
	const uint16_t dim_out_x,
	const uint16_t dim_out_y,
	int32_t *k,
	int32_t *lambda,
	uint8_t * pIm2ColBuffer,
	int8_t * pWtBuffer,
	int flag_relu,
	int flag_batch_norm,
	unsigned int * memory_chan);

void pulp_nn_depthwise_u2_u8_i4(
	const uint8_t * pInBuffer,
	const uint16_t dim_in_x,
	const uint16_t dim_in_y,
	const uint16_t ch_in,
	const int8_t * pWeightBuffer,
	const uint16_t ch_out,
	const uint16_t dim_kernel_x,
	const uint16_t dim_kernel_y,
	const uint16_t padding_y_top,
	const uint16_t padding_y_bottom,
	const uint16_t padding_x_left,
	const uint16_t padding_x_right,
	const uint16_t stride_x,
	const uint16_t stride_y,
	const int8_t * bias,
	const uint16_t bias_shift,
	const int8_t out_shift,
	const uint16_t out_mult,
	uint8_t * pOutBuffer,
	const uint16_t dim_out_x,
	const uint16_t dim_out_y,
	int32_t *k,
	int32_t *lambda,
	uint8_t * pIm2ColBuffer,
	int8_t * pWtBuffer,
	int flag_relu,
	int flag_batch_norm,
	unsigned int * memory_chan);

void pulp_nn_depthwise_u2_u8_i2(
	const uint8_t * pInBuffer,
	const uint16_t dim_in_x,
	const uint16_t dim_in_y,
	const uint16_t ch_in,
	const int8_t * pWeightBuffer,
	const uint16_t ch_out,
	const uint16_t dim_kernel_x,
	const uint16_t dim_kernel_y,
	const uint16_t padding_y_top,
	const uint16_t padding_y_bottom,
	const uint16_t padding_x_left,
	const uint16_t padding_x_right,
	const uint16_t stride_x,
	const uint16_t stride_y,
	const int8_t * bias,
	const uint16_t bias_shift,
	const int8_t out_shift,
	const uint16_t out_mult,
	uint8_t * pOutBuffer,
	const uint16_t dim_out_x,
	const uint16_t dim_out_y,
	int32_t *k,
	int32_t *lambda,
	uint8_t * pIm2ColBuffer,
	int8_t * pWtBuffer,
	int flag_relu,
	int flag_batch_norm,
	unsigned int * memory_chan);

void pulp_nn_depthwise_u2_u4_i8(
	const uint8_t * pInBuffer,
	const uint16_t dim_in_x,
	const uint16_t dim_in_y,
	const uint16_t ch_in,
	const int8_t * pWeightBuffer,
	const uint16_t ch_out,
	const uint16_t dim_kernel_x,
	const uint16_t dim_kernel_y,
	const uint16_t padding_y_top,
	const uint16_t padding_y_bottom,
	const uint16_t padding_x_left,
	const uint16_t padding_x_right,
	const uint16_t stride_x,
	const uint16_t stride_y,
	const int8_t * bias,
	const uint16_t bias_shift,
	const int8_t out_shift,
	const uint16_t out_mult,
	uint8_t * pOutBuffer,
	const uint16_t dim_out_x,
	const uint16_t dim_out_y,
	int32_t *k,
	int32_t *lambda,
	uint8_t * pIm2ColBuffer,
	int8_t * pWtBuffer,
	int flag_relu,
	int flag_batch_norm,
	unsigned int * memory_chan);

void pulp_nn_depthwise_u2_u4_i4(
	const uint8_t * pInBuffer,
	const uint16_t dim_in_x,
	const uint16_t dim_in_y,
	const uint16_t ch_in,
	const int8_t * pWeightBuffer,
	const uint16_t ch_out,
	const uint16_t dim_kernel_x,
	const uint16_t dim_kernel_y,
	const uint16_t padding_y_top,
	const uint16_t padding_y_bottom,
	const uint16_t padding_x_left,
	const uint16_t padding_x_right,
	const uint16_t stride_x,
	const uint16_t stride_y,
	const int8_t * bias,
	const uint16_t bias_shift,
	const int8_t out_shift,
	const uint16_t out_mult,
	uint8_t * pOutBuffer,
	const uint16_t dim_out_x,
	const uint16_t dim_out_y,
	int32_t *k,
	int32_t *lambda,
	uint8_t * pIm2ColBuffer,
	int8_t * pWtBuffer,
	int flag_relu,
	int flag_batch_norm,
	unsigned int * memory_chan);

void pulp_nn_depthwise_u2_u4_i2(
	const uint8_t * pInBuffer,
	const uint16_t dim_in_x,
	const uint16_t dim_in_y,
	const uint16_t ch_in,
	const int8_t * pWeightBuffer,
	const uint16_t ch_out,
	const uint16_t dim_kernel_x,
	const uint16_t dim_kernel_y,
	const uint16_t padding_y_top,
	const uint16_t padding_y_bottom,
	const uint16_t padding_x_left,
	const uint16_t padding_x_right,
	const uint16_t stride_x,
	const uint16_t stride_y,
	const int8_t * bias,
	const uint16_t bias_shift,
	const int8_t out_shift,
	const uint16_t out_mult,
	uint8_t * pOutBuffer,
	const uint16_t dim_out_x,
	const uint16_t dim_out_y,
	int32_t *k,
	int32_t *lambda,
	uint8_t * pIm2ColBuffer,
	int8_t * pWtBuffer,
	int flag_relu,
	int flag_batch_norm,
	unsigned int * memory_chan);

void pulp_nn_depthwise_u2_u2_i8(
	const uint8_t * pInBuffer,
	const uint16_t dim_in_x,
	const uint16_t dim_in_y,
	const uint16_t ch_in,
	const int8_t * pWeightBuffer,
	const uint16_t ch_out,
	const uint16_t dim_kernel_x,
	const uint16_t dim_kernel_y,
	const uint16_t padding_y_top,
	const uint16_t padding_y_bottom,
	const uint16_t padding_x_left,
	const uint16_t padding_x_right,
	const uint16_t stride_x,
	const uint16_t stride_y,
	const int8_t * bias,
	const uint16_t bias_shift,
	const int8_t out_shift,
	const uint16_t out_mult,
	uint8_t * pOutBuffer,
	const uint16_t dim_out_x,
	const uint16_t dim_out_y,
	int32_t *k,
	int32_t *lambda,
	uint8_t * pIm2ColBuffer,
	int8_t * pWtBuffer,
	int flag_relu,
	int flag_batch_norm,
	unsigned int * memory_chan);

void pulp_nn_depthwise_u2_u2_i4(
	const uint8_t * pInBuffer,
	const uint16_t dim_in_x,
	const uint16_t dim_in_y,
	const uint16_t ch_in,
	const int8_t * pWeightBuffer,
	const uint16_t ch_out,
	const uint16_t dim_kernel_x,
	const uint16_t dim_kernel_y,
	const uint16_t padding_y_top,
	const uint16_t padding_y_bottom,
	const uint16_t padding_x_left,
	const uint16_t padding_x_right,
	const uint16_t stride_x,
	const uint16_t stride_y,
	const int8_t * bias,
	const uint16_t bias_shift,
	const int8_t out_shift,
	const uint16_t out_mult,
	uint8_t * pOutBuffer,
	const uint16_t dim_out_x,
	const uint16_t dim_out_y,
	int32_t *k,
	int32_t *lambda,
	uint8_t * pIm2ColBuffer,
	int8_t * pWtBuffer,
	int flag_relu,
	int flag_batch_norm,
	unsigned int * memory_chan);

void pulp_nn_depthwise_u2_u2_i2(
	const uint8_t * pInBuffer,
	const uint16_t dim_in_x,
	const uint16_t dim_in_y,
	const uint16_t ch_in,
	const int8_t * pWeightBuffer,
	const uint16_t ch_out,
	const uint16_t dim_kernel_x,
	const uint16_t dim_kernel_y,
	const uint16_t padding_y_top,
	const uint16_t padding_y_bottom,
	const uint16_t padding_x_left,
	const uint16_t padding_x_right,
	const uint16_t stride_x,
	const uint16_t stride_y,
	const int8_t * bias,
	const uint16_t bias_shift,
	const int8_t out_shift,
	const uint16_t out_mult,
	uint8_t * pOutBuffer,
	const uint16_t dim_out_x,
	const uint16_t dim_out_y,
	int32_t *k,
	int32_t *lambda,
	uint8_t * pIm2ColBuffer,
	int8_t * pWtBuffer,
	int flag_relu,
	int flag_batch_norm,
	unsigned int * memory_chan);

void pulp_nn_linear_u8_i32_i8(
	uint8_t *pInBuffer,
	int8_t *pWeights,
	uint16_t dim_vec,
	uint16_t num_o_neurons,
	int8_t *bias,
	uint16_t bias_shift,
	int8_t out_shift,
	uint16_t out_mult,
	int32_t *k,
	int32_t *lambda,
	uint8_t *pOutBuffer,
	int flag_relu,
	int flag_batch_norm,
	unsigned int * memory_chan);

void pulp_nn_linear_u8_i32_i4(
	uint8_t *pInBuffer,
	int8_t *pWeights,
	uint16_t dim_vec,
	uint16_t num_o_neurons,
	int8_t *bias,
	uint16_t bias_shift,
	int8_t out_shift,
	uint16_t out_mult,
	int32_t *k,
	int32_t *lambda,
	uint8_t *pOutBuffer,
	int flag_relu,
	int flag_batch_norm,
	unsigned int * memory_chan);

void pulp_nn_linear_u8_i32_i2(
	uint8_t *pInBuffer,
	int8_t *pWeights,
	uint16_t dim_vec,
	uint16_t num_o_neurons,
	int8_t *bias,
	uint16_t bias_shift,
	int8_t out_shift,
	uint16_t out_mult,
	int32_t *k,
	int32_t *lambda,
	uint8_t *pOutBuffer,
	int flag_relu,
	int flag_batch_norm,
	unsigned int * memory_chan);

void pulp_nn_linear_u4_i32_i8(
	uint8_t *pInBuffer,
	int8_t *pWeights,
	uint16_t dim_vec,
	uint16_t num_o_neurons,
	int8_t *bias,
	uint16_t bias_shift,
	int8_t out_shift,
	uint16_t out_mult,
	int32_t *k,
	int32_t *lambda,
	uint8_t *pOutBuffer,
	int flag_relu,
	int flag_batch_norm,
	unsigned int * memory_chan);

void pulp_nn_linear_u4_i32_i4(
	uint8_t *pInBuffer,
	int8_t *pWeights,
	uint16_t dim_vec,
	uint16_t num_o_neurons,
	int8_t *bias,
	uint16_t bias_shift,
	int8_t out_shift,
	uint16_t out_mult,
	int32_t *k,
	int32_t *lambda,
	uint8_t *pOutBuffer,
	int flag_relu,
	int flag_batch_norm,
	unsigned int * memory_chan);

void pulp_nn_linear_u4_i32_i2(
	uint8_t *pInBuffer,
	int8_t *pWeights,
	uint16_t dim_vec,
	uint16_t num_o_neurons,
	int8_t *bias,
	uint16_t bias_shift,
	int8_t out_shift,
	uint16_t out_mult,
	int32_t *k,
	int32_t *lambda,
	uint8_t *pOutBuffer,
	int flag_relu,
	int flag_batch_norm,
	unsigned int * memory_chan);

void pulp_nn_linear_u2_i32_i8(
	uint8_t *pInBuffer,
	int8_t *pWeights,
	uint16_t dim_vec,
	uint16_t num_o_neurons,
	int8_t *bias,
	uint16_t bias_shift,
	int8_t out_shift,
	uint16_t out_mult,
	int32_t *k,
	int32_t *lambda,
	uint8_t *pOutBuffer,
	int flag_relu,
	int flag_batch_norm,
	unsigned int * memory_chan);

void pulp_nn_linear_u2_i32_i4(
	uint8_t *pInBuffer,
	int8_t *pWeights,
	uint16_t dim_vec,
	uint16_t num_o_neurons,
	int8_t *bias,
	uint16_t bias_shift,
	int8_t out_shift,
	uint16_t out_mult,
	int32_t *k,
	int32_t *lambda,
	uint8_t *pOutBuffer,
	int flag_relu,
	int flag_batch_norm,
	unsigned int * memory_chan);

void pulp_nn_linear_u2_i32_i2(
	uint8_t *pInBuffer,
	int8_t *pWeights,
	uint16_t dim_vec,
	uint16_t num_o_neurons,
	int8_t *bias,
	uint16_t bias_shift,
	int8_t out_shift,
	uint16_t out_mult,
	int32_t *k,
	int32_t *lambda,
	uint8_t *pOutBuffer,
	int flag_relu,
	int flag_batch_norm,
	unsigned int * memory_chan);

void pulp_nn_linear_u8_u8_i8(
	uint8_t *pInBuffer,
	int8_t *pWeights,
	uint16_t dim_vec,
	uint16_t num_o_neurons,
	int8_t *bias,
	uint16_t bias_shift,
	int8_t out_shift,
	uint16_t out_mult,
	int32_t *k,
	int32_t *lambda,
	uint8_t *pOutBuffer,
	int flag_relu,
	int flag_batch_norm,
	unsigned int * memory_chan);

void pulp_nn_linear_u8_u8_i4(
	uint8_t *pInBuffer,
	int8_t *pWeights,
	uint16_t dim_vec,
	uint16_t num_o_neurons,
	int8_t *bias,
	uint16_t bias_shift,
	int8_t out_shift,
	uint16_t out_mult,
	int32_t *k,
	int32_t *lambda,
	uint8_t *pOutBuffer,
	int flag_relu,
	int flag_batch_norm,
	unsigned int * memory_chan);

void pulp_nn_linear_u8_u8_i2(
	uint8_t *pInBuffer,
	int8_t *pWeights,
	uint16_t dim_vec,
	uint16_t num_o_neurons,
	int8_t *bias,
	uint16_t bias_shift,
	int8_t out_shift,
	uint16_t out_mult,
	int32_t *k,
	int32_t *lambda,
	uint8_t *pOutBuffer,
	int flag_relu,
	int flag_batch_norm,
	unsigned int * memory_chan);

void pulp_nn_linear_u8_u4_i8(
	uint8_t *pInBuffer,
	int8_t *pWeights,
	uint16_t dim_vec,
	uint16_t num_o_neurons,
	int8_t *bias,
	uint16_t bias_shift,
	int8_t out_shift,
	uint16_t out_mult,
	int32_t *k,
	int32_t *lambda,
	uint8_t *pOutBuffer,
	int flag_relu,
	int flag_batch_norm,
	unsigned int * memory_chan);

void pulp_nn_linear_u8_u4_i4(
	uint8_t *pInBuffer,
	int8_t *pWeights,
	uint16_t dim_vec,
	uint16_t num_o_neurons,
	int8_t *bias,
	uint16_t bias_shift,
	int8_t out_shift,
	uint16_t out_mult,
	int32_t *k,
	int32_t *lambda,
	uint8_t *pOutBuffer,
	int flag_relu,
	int flag_batch_norm,
	unsigned int * memory_chan);

void pulp_nn_linear_u8_u4_i2(
	uint8_t *pInBuffer,
	int8_t *pWeights,
	uint16_t dim_vec,
	uint16_t num_o_neurons,
	int8_t *bias,
	uint16_t bias_shift,
	int8_t out_shift,
	uint16_t out_mult,
	int32_t *k,
	int32_t *lambda,
	uint8_t *pOutBuffer,
	int flag_relu,
	int flag_batch_norm,
	unsigned int * memory_chan);

void pulp_nn_linear_u8_u2_i8(
	uint8_t *pInBuffer,
	int8_t *pWeights,
	uint16_t dim_vec,
	uint16_t num_o_neurons,
	int8_t *bias,
	uint16_t bias_shift,
	int8_t out_shift,
	uint16_t out_mult,
	int32_t *k,
	int32_t *lambda,
	uint8_t *pOutBuffer,
	int flag_relu,
	int flag_batch_norm,
	unsigned int * memory_chan);

void pulp_nn_linear_u8_u2_i4(
	uint8_t *pInBuffer,
	int8_t *pWeights,
	uint16_t dim_vec,
	uint16_t num_o_neurons,
	int8_t *bias,
	uint16_t bias_shift,
	int8_t out_shift,
	uint16_t out_mult,
	int32_t *k,
	int32_t *lambda,
	uint8_t *pOutBuffer,
	int flag_relu,
	int flag_batch_norm,
	unsigned int * memory_chan);

void pulp_nn_linear_u8_u2_i2(
	uint8_t *pInBuffer,
	int8_t *pWeights,
	uint16_t dim_vec,
	uint16_t num_o_neurons,
	int8_t *bias,
	uint16_t bias_shift,
	int8_t out_shift,
	uint16_t out_mult,
	int32_t *k,
	int32_t *lambda,
	uint8_t *pOutBuffer,
	int flag_relu,
	int flag_batch_norm,
	unsigned int * memory_chan);

void pulp_nn_linear_u4_u8_i8(
	uint8_t *pInBuffer,
	int8_t *pWeights,
	uint16_t dim_vec,
	uint16_t num_o_neurons,
	int8_t *bias,
	uint16_t bias_shift,
	int8_t out_shift,
	uint16_t out_mult,
	int32_t *k,
	int32_t *lambda,
	uint8_t *pOutBuffer,
	int flag_relu,
	int flag_batch_norm,
	unsigned int * memory_chan);

void pulp_nn_linear_u4_u8_i4(
	uint8_t *pInBuffer,
	int8_t *pWeights,
	uint16_t dim_vec,
	uint16_t num_o_neurons,
	int8_t *bias,
	uint16_t bias_shift,
	int8_t out_shift,
	uint16_t out_mult,
	int32_t *k,
	int32_t *lambda,
	uint8_t *pOutBuffer,
	int flag_relu,
	int flag_batch_norm,
	unsigned int * memory_chan);

void pulp_nn_linear_u4_u8_i2(
	uint8_t *pInBuffer,
	int8_t *pWeights,
	uint16_t dim_vec,
	uint16_t num_o_neurons,
	int8_t *bias,
	uint16_t bias_shift,
	int8_t out_shift,
	uint16_t out_mult,
	int32_t *k,
	int32_t *lambda,
	uint8_t *pOutBuffer,
	int flag_relu,
	int flag_batch_norm,
	unsigned int * memory_chan);

void pulp_nn_linear_u4_u4_i8(
	uint8_t *pInBuffer,
	int8_t *pWeights,
	uint16_t dim_vec,
	uint16_t num_o_neurons,
	int8_t *bias,
	uint16_t bias_shift,
	int8_t out_shift,
	uint16_t out_mult,
	int32_t *k,
	int32_t *lambda,
	uint8_t *pOutBuffer,
	int flag_relu,
	int flag_batch_norm,
	unsigned int * memory_chan);

void pulp_nn_linear_u4_u4_i4(
	uint8_t *pInBuffer,
	int8_t *pWeights,
	uint16_t dim_vec,
	uint16_t num_o_neurons,
	int8_t *bias,
	uint16_t bias_shift,
	int8_t out_shift,
	uint16_t out_mult,
	int32_t *k,
	int32_t *lambda,
	uint8_t *pOutBuffer,
	int flag_relu,
	int flag_batch_norm,
	unsigned int * memory_chan);

void pulp_nn_linear_u4_u4_i2(
	uint8_t *pInBuffer,
	int8_t *pWeights,
	uint16_t dim_vec,
	uint16_t num_o_neurons,
	int8_t *bias,
	uint16_t bias_shift,
	int8_t out_shift,
	uint16_t out_mult,
	int32_t *k,
	int32_t *lambda,
	uint8_t *pOutBuffer,
	int flag_relu,
	int flag_batch_norm,
	unsigned int * memory_chan);

void pulp_nn_linear_u4_u2_i8(
	uint8_t *pInBuffer,
	int8_t *pWeights,
	uint16_t dim_vec,
	uint16_t num_o_neurons,
	int8_t *bias,
	uint16_t bias_shift,
	int8_t out_shift,
	uint16_t out_mult,
	int32_t *k,
	int32_t *lambda,
	uint8_t *pOutBuffer,
	int flag_relu,
	int flag_batch_norm,
	unsigned int * memory_chan);

void pulp_nn_linear_u4_u2_i4(
	uint8_t *pInBuffer,
	int8_t *pWeights,
	uint16_t dim_vec,
	uint16_t num_o_neurons,
	int8_t *bias,
	uint16_t bias_shift,
	int8_t out_shift,
	uint16_t out_mult,
	int32_t *k,
	int32_t *lambda,
	uint8_t *pOutBuffer,
	int flag_relu,
	int flag_batch_norm,
	unsigned int * memory_chan);

void pulp_nn_linear_u4_u2_i2(
	uint8_t *pInBuffer,
	int8_t *pWeights,
	uint16_t dim_vec,
	uint16_t num_o_neurons,
	int8_t *bias,
	uint16_t bias_shift,
	int8_t out_shift,
	uint16_t out_mult,
	int32_t *k,
	int32_t *lambda,
	uint8_t *pOutBuffer,
	int flag_relu,
	int flag_batch_norm,
	unsigned int * memory_chan);

void pulp_nn_linear_u2_u8_i8(
	uint8_t *pInBuffer,
	int8_t *pWeights,
	uint16_t dim_vec,
	uint16_t num_o_neurons,
	int8_t *bias,
	uint16_t bias_shift,
	int8_t out_shift,
	uint16_t out_mult,
	int32_t *k,
	int32_t *lambda,
	uint8_t *pOutBuffer,
	int flag_relu,
	int flag_batch_norm,
	unsigned int * memory_chan);

void pulp_nn_linear_u2_u8_i4(
	uint8_t *pInBuffer,
	int8_t *pWeights,
	uint16_t dim_vec,
	uint16_t num_o_neurons,
	int8_t *bias,
	uint16_t bias_shift,
	int8_t out_shift,
	uint16_t out_mult,
	int32_t *k,
	int32_t *lambda,
	uint8_t *pOutBuffer,
	int flag_relu,
	int flag_batch_norm,
	unsigned int * memory_chan);

void pulp_nn_linear_u2_u8_i2(
	uint8_t *pInBuffer,
	int8_t *pWeights,
	uint16_t dim_vec,
	uint16_t num_o_neurons,
	int8_t *bias,
	uint16_t bias_shift,
	int8_t out_shift,
	uint16_t out_mult,
	int32_t *k,
	int32_t *lambda,
	uint8_t *pOutBuffer,
	int flag_relu,
	int flag_batch_norm,
	unsigned int * memory_chan);

void pulp_nn_linear_u2_u4_i8(
	uint8_t *pInBuffer,
	int8_t *pWeights,
	uint16_t dim_vec,
	uint16_t num_o_neurons,
	int8_t *bias,
	uint16_t bias_shift,
	int8_t out_shift,
	uint16_t out_mult,
	int32_t *k,
	int32_t *lambda,
	uint8_t *pOutBuffer,
	int flag_relu,
	int flag_batch_norm,
	unsigned int * memory_chan);

void pulp_nn_linear_u2_u4_i4(
	uint8_t *pInBuffer,
	int8_t *pWeights,
	uint16_t dim_vec,
	uint16_t num_o_neurons,
	int8_t *bias,
	uint16_t bias_shift,
	int8_t out_shift,
	uint16_t out_mult,
	int32_t *k,
	int32_t *lambda,
	uint8_t *pOutBuffer,
	int flag_relu,
	int flag_batch_norm,
	unsigned int * memory_chan);

void pulp_nn_linear_u2_u4_i2(
	uint8_t *pInBuffer,
	int8_t *pWeights,
	uint16_t dim_vec,
	uint16_t num_o_neurons,
	int8_t *bias,
	uint16_t bias_shift,
	int8_t out_shift,
	uint16_t out_mult,
	int32_t *k,
	int32_t *lambda,
	uint8_t *pOutBuffer,
	int flag_relu,
	int flag_batch_norm,
	unsigned int * memory_chan);

void pulp_nn_linear_u2_u2_i8(
	uint8_t *pInBuffer,
	int8_t *pWeights,
	uint16_t dim_vec,
	uint16_t num_o_neurons,
	int8_t *bias,
	uint16_t bias_shift,
	int8_t out_shift,
	uint16_t out_mult,
	int32_t *k,
	int32_t *lambda,
	uint8_t *pOutBuffer,
	int flag_relu,
	int flag_batch_norm,
	unsigned int * memory_chan);

void pulp_nn_linear_u2_u2_i4(
	uint8_t *pInBuffer,
	int8_t *pWeights,
	uint16_t dim_vec,
	uint16_t num_o_neurons,
	int8_t *bias,
	uint16_t bias_shift,
	int8_t out_shift,
	uint16_t out_mult,
	int32_t *k,
	int32_t *lambda,
	uint8_t *pOutBuffer,
	int flag_relu,
	int flag_batch_norm,
	unsigned int * memory_chan);

void pulp_nn_linear_u2_u2_i2(
	uint8_t *pInBuffer,
	int8_t *pWeights,
	uint16_t dim_vec,
	uint16_t num_o_neurons,
	int8_t *bias,
	uint16_t bias_shift,
	int8_t out_shift,
	uint16_t out_mult,
	int32_t *k,
	int32_t *lambda,
	uint8_t *pOutBuffer,
	int flag_relu,
	int flag_batch_norm,
	unsigned int * memory_chan);

void pulp_nn_maxpool_u8(
	uint8_t * Im_in,
	uint16_t  dim_im_in_x,
	uint16_t  dim_im_in_y,
	uint16_t  ch_im_in,
	uint16_t  dim_kernel,
	uint16_t  padding_t,
	uint16_t  padding_b,
	uint16_t  padding_l,
	uint16_t  padding_r,
	uint16_t  stride,
	uint16_t  dim_im_out_x,
	uint16_t  dim_im_out_y,
	uint8_t * Im_out,
	unsigned int * memory_chan);

void pulp_nn_maxpool_u4(
	uint8_t * Im_in,
	uint16_t  dim_im_in_x,
	uint16_t  dim_im_in_y,
	uint16_t  ch_im_in,
	uint16_t  dim_kernel,
	uint16_t  padding_t,
	uint16_t  padding_b,
	uint16_t  padding_l,
	uint16_t  padding_r,
	uint16_t  stride,
	uint16_t  dim_im_out_x,
	uint16_t  dim_im_out_y,
	uint8_t * Im_out,
	unsigned int * memory_chan);

void pulp_nn_maxpool_u2(
	uint8_t * Im_in,
	uint16_t  dim_im_in_x,
	uint16_t  dim_im_in_y,
	uint16_t  ch_im_in,
	uint16_t  dim_kernel,
	uint16_t  padding_t,
	uint16_t  padding_b,
	uint16_t  padding_l,
	uint16_t  padding_r,
	uint16_t  stride,
	uint16_t  dim_im_out_x,
	uint16_t  dim_im_out_y,
	uint8_t * Im_out,
	unsigned int * memory_chan);

void pulp_nn_avgpool_u8(
	uint8_t * Im_in,
	uint16_t dim_im_in,
	uint16_t ch_im_in,
	uint16_t dim_kernel,
	uint16_t padding,
	uint16_t stride,
	uint16_t dim_im_out,
	uint8_t * Im_out,
	unsigned int * memory_chan);

void pulp_nn_avgpool_u4(
	uint8_t * Im_in,
	uint16_t dim_im_in,
	uint16_t ch_im_in,
	uint16_t dim_kernel,
	uint16_t padding,
	uint16_t stride,
	uint16_t dim_im_out,
	uint8_t * Im_out,
	unsigned int * memory_chan);

void pulp_nn_avgpool_u2(
	uint8_t * Im_in,
	uint16_t dim_im_in,
	uint16_t ch_im_in,
	uint16_t dim_kernel,
	uint16_t padding,
	uint16_t stride,
	uint16_t dim_im_out,
	uint8_t * Im_out,
	unsigned int * memory_chan);

void pulp_nn_add_u8_u8(
	uint8_t * Im_in_1,    
	uint8_t * Im_in_2,    
	uint16_t  ch_im_in,   
	uint16_t  dim_im_in_h,
	uint16_t  dim_im_in_w,
	uint8_t * Im_out,     
	uint16_t out_mult1,   
	uint16_t out_mult2,   
	uint16_t out_shift    
);

void pulp_nn_add_u8_u4(
	uint8_t * Im_in_1,    
	uint8_t * Im_in_2,    
	uint16_t  ch_im_in,   
	uint16_t  dim_im_in_h,
	uint16_t  dim_im_in_w,
	uint8_t * Im_out,     
	uint16_t out_mult1,   
	uint16_t out_mult2,   
	uint16_t out_shift    
);

void pulp_nn_add_u8_u2(
	uint8_t * Im_in_1,    
	uint8_t * Im_in_2,    
	uint16_t  ch_im_in,   
	uint16_t  dim_im_in_h,
	uint16_t  dim_im_in_w,
	uint8_t * Im_out,     
	uint16_t out_mult1,   
	uint16_t out_mult2,   
	uint16_t out_shift    
);

void pulp_nn_add_u4_u4(
	uint8_t * Im_in_1,    
	uint8_t * Im_in_2,    
	uint16_t  ch_im_in,   
	uint16_t  dim_im_in_h,
	uint16_t  dim_im_in_w,
	uint8_t * Im_out,     
	uint16_t out_mult1,   
	uint16_t out_mult2,   
	uint16_t out_shift    
);

void pulp_nn_add_u4_u2(
	uint8_t * Im_in_1,    
	uint8_t * Im_in_2,    
	uint16_t  ch_im_in,   
	uint16_t  dim_im_in_h,
	uint16_t  dim_im_in_w,
	uint8_t * Im_out,     
	uint16_t out_mult1,   
	uint16_t out_mult2,   
	uint16_t out_shift    
);

void pulp_nn_add_u2_u2(
	uint8_t * Im_in_1,    
	uint8_t * Im_in_2,    
	uint16_t  ch_im_in,   
	uint16_t  dim_im_in_h,
	uint16_t  dim_im_in_w,
	uint8_t * Im_out,     
	uint16_t out_mult1,   
	uint16_t out_mult2,   
	uint16_t out_shift    
);



#endif